### ISSUE TITLE
 TypeError: Cannot read property 'querySelector' of undefined in FastBoot

### ISSUE THREAD

**Issue by josemarluedke** [cibernox/ember-basic-dropdown#105]
After fixing cibernox/ember-power-select#543 this bug happens when running on fastboot.

`TypeError: Cannot read property 'querySelector' of undefined`

I suspect that this is happening here: https://github.com/cibernox/ember-basic-dropdown/blob/fa5949ad1940893abbac02fa5f5929cc256d9bab/addon/components/basic-dropdown.js#L55

**Comment by josemarluedke** [comment]
I hope to get #116 merged with the fix, mean while I have published my test app with the reproduction of the error at https://github.com/josemarluedke/test-app-fastboot!

Thanks @Rastopyr for stepping in and fixing the problem.

**Comment by Rastopyr** [comment]
@josemarluedke np! 👍

**Comment by Rastopyr** [comment]
@cibernox we are fixed API for correct FastBoot rendering, so will be any updates for publishing new version of `ember-basic-dropdown` in npm registry?

i think is very matter for correct work of `ember-power-select`.

**Comment by cibernox** [comment]
Published a new version. Given that the dependency of EPS in EBD is loose, deleting EBD in your node_modules folder and install again should be enough
