### ISSUE TITLE
Could not find module `ember-owner/get` imported from `ember-basic-dropdown/components/basic-dropdown`

### ISSUE THREAD

**Issue by arnaldo2792** [cibernox/ember-basic-dropdown#126]
Hi!!

Using Ember 2.7.0 I got this error, the [documentation](http://emberjs.com/deprecations/v2.x/#toc_injected-container-access) said that `getOwner` should be imported as `const { getOwner } = Ember;`.

I'm using it through `ember-power-select`.

**Comment by cibernox** [comment]
Updating `ember-cli-shims` to 0.1.3 in your bower.json should fix it.
