### ISSUE TITLE
Uncaught TypeError: (0 , _emberMetalUtils.guidFor) is not a function

### ISSUE THREAD

**Issue by ryanlitalien** [cibernox/ember-basic-dropdown#141]
Hi @cibernox,
I just installed ember-power-select and took the basic template example and put it in a simple HBS and I'm getting this error. I see you've changed around the `guidFor` recently. Any suggestions?

![image](https://cloud.githubusercontent.com/assets/1479756/18010325/fee877ac-6b7d-11e6-831b-ba5df689c1ac.png)

**Comment by cibernox** [comment]
@ryanlitalien Wipe your nodemodules and install again to get the latest version of `ember-basic-dropdown`. That version has the fix.

Aternatively you can update `ember-cli-shims` in your bower.json to `0.1.3` or bigger. That would also work.
