### ISSUE TITLE
How can I close opened dropdown?

### ISSUE THREAD

**Issue by kaermorchen** [cibernox/ember-basic-dropdown#159]
I have this code:
```
{{#basic-dropdown disabled=(not selectedEvents.length) isOpen=eventsActionsIsOpen as |dropdown|}}
      {{#dropdown.trigger}}
        <button class="button margin-bottom-0" disabled={{not selectedEvents.length}}><i class="mdi mdi-dots-vertical"></i> Действия</button>
      {{/dropdown.trigger}}
      {{#dropdown.content}}
        <ul class="dropdown menu vertical">
          <li class="dropdown-item" {{action 'cancelEvents'}}>Отменить</li>
          <li class="dropdown-item" {{action 'deleteEvents'}}>Удалить</li>
        </ul>
      {{/dropdown.content}}
    {{/basic-dropdown}}
```
```
  actions: {
    cancelEvents() {
      ...
      this.set('eventsActionsIsOpen', false);
    }
  }
```

But it don't work. How can I close opened dropdown?

**Comment by irruputuncu** [comment]
I had the same problem and solved it by using the close action of the public API of the dropdown object, similar to this: 

```
{{#basic-dropdown disabled=(not selectedEvents.length) as |dropdown|}}
      {{#dropdown.trigger}}
        ...
      {{/dropdown.trigger}}
      {{#dropdown.content}}
        <ul class="dropdown menu vertical">
          <li class="dropdown-item" {{action 'cancelEvents' dropdown}}>Отменить</li>
          <li class="dropdown-item" {{action 'deleteEvents'}}>Удалить</li>
        </ul>
      {{/dropdown.content}}
    {{/basic-dropdown}}
```

```
  actions: {
    cancelEvents(dropdown) {
      ...
      dropdown.actions.close();
    }
  }
```

**Comment by cibernox** [comment]
@irruputuncu Yes, that is the right answer. The `dropdown` object contains the public API to interact with the dropdown in any way.

**Comment by yvone-kioru** [comment]
@cibernox how about having to close the dropdown and pass data up for an parent action thats waiting for the value? is there a way to send the action both: dropdown and new selected value? thanks!

**Comment by cibernox** [comment]
@yvone-kioru could you give me more information? I'm not sure I get exactly your use case

**Comment by yvone-kioru** [comment]
@cibernox i actually made it work with the `dropbox` object, thanks! my use case was a custom component for the basic dropdown, having an input as the trigger and `power-calendar` as the content. Then when selecting a day, it should close the `dropdown` and also trigger the action passed by whoever implemented the component. I solved it by having an action in the controller of the component and using the dropdown object with the close action and then passing the action up.

**Comment by christina-ng** [comment]
@yvone-kioru Can you post your solution? I'm also trying to figure out how to create an external input trigger.
