### ISSUE TITLE
Could not find module `ember-get-config` imported from `ember-basic-dropdown/components/basic-dropdown/content`

### ISSUE THREAD

**Issue by orf** [cibernox/ember-basic-dropdown#161]
Hey, with the latest release we are getting an error in our tests:

`Could not find module `ember-get-config` imported from `ember-basic-dropdown/components/basic-dropdown/content`

Pinning `ember-basic-dropdown` to `0.16.0-beta.4` or `ember-get-config` to `0.1.7` works fine, so it seems something has broken in the latest release of either of those.

We are pulling this library in from `ember-power-select.

**Comment by SaladFork** [comment]
Seeing similar. Works fine with `ember-power-select@1.0.0-beta.18` but fails with the mentioned error with `ember-power-select@1.0.0-beta.19`. It seems [this changed](https://github.com/cibernox/ember-power-select/compare/v1.0.0-beta.18...v1.0.0-beta.19) from including `ember-basic-dropdown@0.16.0-beta.3` to `ember-basic-dropdown@0.16.0-beta.4`.

**Comment by cibernox** [comment]
I've just published a new version of EBD that doesn't use `ember-get-config` at all. Given that the dependency of EPS in EBD is relaxed (`^`) removing `node_modules` and installing again is enough.

Let me know if this works.

**Comment by jdurand** [comment]
@cibernox if it's easily doable, you should consider yanking out ember-basic-dropdown@0.16.0-beta.5

**Comment by SaladFork** [comment]
I can confirm that the reinstalled `1.0.0-beta.19` no longer throws this error. Thanks!

**Comment by cibernox** [comment]
@jdurand I did if a while ago actually

**Comment by jdurand** [comment]
@cibernox odd it was probably still in cache somewhere because I hit this issue this morning (EST).
