### ISSUE TITLE
Always use integral values for dropdown position and dimensions

### ISSUE THREAD

**Issue by Dremora** [cibernox/ember-basic-dropdown#174]
Fractional dropdown width causes surprising behaviour with certain styles in Chrome 54. Please see this [JSfiddle](https://jsfiddle.net/dL4w5y66/). You should observe a 1px vertical red line, despite inner and outer container having the same width.
Even though this is a Chrome bug, I don't think that it makes sense to operate on subpixel level. Or does it?

**Comment by Dremora** [comment]
Just submitted a [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=665619) to Chromium.

**Comment by cibernox** [comment]
I wasn't even aware that I operate at sub-pixel level. I guess that I'll operate at that level if `getBoundingClientRect` does. I'm not sure what might happen if I round values.

Did worked well in Chrome 53?

**Comment by Dremora** [comment]
I don't know if it did. It's a new design we have just implemented:
<img width="318" alt="screen shot 2016-11-17 at 13 27 31" src="https://cloud.githubusercontent.com/assets/242202/20391072/a304c106-acc9-11e6-88f4-3ea03f7c6b81.png">
Note that the highlighted items are now covering dropdown's border. This is done by setting `margin: 0 -1px` on `.ember-power-select-options[role="listbox"]`.
This, however, breaks on dropdowns with groups:
<img width="281" alt="screen shot 2016-11-17 at 13 26 45" src="https://cloud.githubusercontent.com/assets/242202/20391057/89665a34-acc9-11e6-8e09-c609ede59f73.png">
It seems that adding an extra level of nesting incorrectly propagates parent's dimensions to the child.
