### ISSUE TITLE
Modifying Ember 2.10 hPosition

### ISSUE THREAD

**Issue by snewcomer** [cibernox/ember-basic-dropdown#175]
Upgrading to 2.10 shows this error in an acceptance test run.  In one of the tests, for ex//, I am using `selectChoose` to modify a few power selects on the page.  Do you think this is this a symptom of my code/test or how basic-dropdown is used in power select?  Looks like the hPosition is used in the trigger and content sections of ember-basic-dropdown.  On beta.31 of power select btw.

![screen shot 2016-11-30 at 1 42 06 pm](https://cloud.githubusercontent.com/assets/7374640/20772559/ce96fb66-b702-11e6-9bba-6903d8305922.png)

https://github.com/emberjs/ember.js/issues/13948

**Comment by cibernox** [comment]
Interesting. Can you create a reproduction? I've used in in acceptance tests and I haven't seen this error.

**Comment by cibernox** [comment]
@snewcomer I think I've fixed it in the latest beta of power-dropdown. Check it.

**Comment by snewcomer** [comment]
seems to have fixed it.  Thanks!
