### ISSUE TITLE
How to show "run-loop" error caused by this library (when used by power-select)

### ISSUE THREAD

**Issue by toranb** [cibernox/ember-basic-dropdown#18]
The run-loop issue we talked about on power-select a week ago is still present in the latest beta 4 because of the way "repositionDropdown" is invoked without a run loop (tests show this in firefox and chrome in our app).

https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components/basic-dropdown.js#L167

The line above isn't under a "run" right now, but when I add a ember.run here all our tests suddenly pass (making me think we should protect the set that occurs here)

https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components/basic-dropdown.js#L136

I'm opening this in part to help us fix the run-loop issue we found, but also to ask "how can we /where should we" test it today as the bug only occurs because of an if statement we invalidate (causing a re-render in HTMLBars)

https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select/single.hbs#L26

What happens in our search action is - we debounce like so

```js
Ember.run.debounce(this, myFunction, search, 300);
```

This in turn changes a url query param that updates the underlying options and when those underlying options go from zero (empty array proxy in my case) to something else that if statement is evaluated and fired to render the options (and that render fires the repositionDropdown you see above causing run-loop issues in test code).

I'm planning to submit a PR here (to fix the root cause) if that's acceptable - any other info that may help me as I diagnose this ?

here is the stack showing that our HTMLBars if (in power-select) changes causing a render to run -thus invoking the reposition work 

![screen shot 2015-11-24 at 1 05 38 pm](https://cloud.githubusercontent.com/assets/147411/11377582/302c1d4c-92ac-11e5-80ad-912fd826d017.png)

**Comment by cibernox** [comment]
Seems reasonable to run callback of the mutatin inside a runloop. However since it's called from a couple places I've made this change instead: https://github.com/cibernox/ember-basic-dropdown/commit/db4b721ee6731b678ad71c0aaf2dbb9263d7bb91

I'm going to include this next beta of ember-power-select to see if it fixes the issue. Doing nombom, might take ~15 minutes

**Comment by cibernox** [comment]
Published ember-power-select 0.6.0-beta.5, give it a try to see if that fixes the problem in testing.

**Comment by toranb** [comment]
Thanks for the quick release - I have a half baked/almost working test for this but can't seem to find how you tested/ verify the mutation work. This commit shows no tests/etc so how can I test this (even at the acceptance level without power-select) ?

https://github.com/cibernox/ember-basic-dropdown/commit/64b54b82e34f2100749d2fab56510b68394e3511

**Comment by cibernox** [comment]
I think that is because I didn't. I couldn't figure out a way of validate at an acceptance level that the mutation observer is doing it's job because the only way would probably assert that the dropdown is correctly positioned, and since tests in qunit run within this small div that is tricky to validate.

How were you testing it?

**Comment by snewcomer** [comment]
```js
import Ember from 'ember';
import { test, module } from 'qunit';
import startApp from 'dummy/tests/helpers/start-app';

var application, func, runs, original;

var MonkeyPatchedObserver = (function() {
    var factory = function(callback) {
        func = callback;
    };
    factory.prototype.observe = function() {
    };
    factory.prototype.disconnect = function() {
    };
    return factory;
})();

window.MutationObserver = MonkeyPatchedObserver;

module('Acceptance | runloop-aware', {
    beforeEach() {
        application = startApp();
    },
    afterEach() {
        Ember.run(application, 'destroy');
    }
});

test('repositionDropdown should be run loop aware on re-render', function(assert) {
    var mutations = [{addedNodes: {length: 1}}];
    var done = assert.async();
    visit('/runloop');
    click('.ember-basic-dropdown-trigger');
    andThen(function() {
        func(mutations);
        setTimeout(function() {
            assert.equal(1, 1);
            done();
        }, 1);
    });
});
```

**Comment by toranb** [comment]
@cibernox what you see above is what we have but it all fell down once we got inside the repositionDropdown function (after invoking the callback manually in the test after having monkey patched the MutationObserver itself). Not great as you can see but I really, really, really wanted to see some of this code under test ....
