### ISSUE TITLE
`verticalPosition` does not work with `renderInPlace`

### ISSUE THREAD

**Issue by SaladFork** [cibernox/ember-basic-dropdown#184]
```hbs
{{! has class ".ember-basic-dropdown-content--above" }}
{{#basic-dropdown verticalPosition="above" renderInPlace=false}}

{{! does not have any vertical position class }}
{{#basic-dropdown verticalPosition="above" renderInPlace=true}}
```

**Comment by cibernox** [comment]
Yeah, this is expected. When rendered in place, the dropdown is physically placed in the DOM below the trigger. It cannot be positioned above

**Comment by SaladFork** [comment]
It's still positioned absolutely though. Couldn't we, for example, set `bottom` so it visually appears above the trigger?

**Comment by cibernox** [comment]
Unsure, I never tried. It  guess that the parent has to be relative, but could work.

**Comment by SaladFork** [comment]
`ember-basic-dropdown`, the parent, is already positioned relatively. As far as I can tell this is how the dropdown content is positioned in most cases.

**Comment by SaladFork** [comment]
Added by #186 :)
