### ISSUE TITLE
Body height is required to trigger close on click

### ISSUE THREAD

**Issue by karellm** [cibernox/ember-basic-dropdown#196]
I'm working on a new app with just a header, so the body has a height of just 40px. Clicking anywhere but on the header (aka `body`) would fail to close the modal.

A simple css line fixed that: `body {min-height: 100vh;}`. 

It is unlikely to happen in an actual app and not a bug per say but I thought I would share anyway. Maybe it could be added to the docs.

**Comment by cibernox** [comment]
Yes, that might surprise someone. Could you create a PR that adds a note on the Readme.md?
