### ISSUE TITLE
Should ember-native-dom-helpers be in dependencies, rather than devDependencies?

### ISSUE THREAD

**Issue by paulcwatts** [cibernox/ember-basic-dropdown#231]
I was including `clickTrigger` in a component integration test like this:

```javascript
import { clickTrigger } from '../../helpers/ember-basic-dropdown';
```

When I upgraded from v0.24.2 to v0.24.4, I got the error:

```
Error: Could not find module `ember-native-dom-helpers/test-support/helpers` imported from `tycho/tests/helpers/ember-basic-dropdown`
TypeError: Cannot read property 'exports' of undefined at http://localhost:7357/assets/test-support.js, line 5774
```

ember-native-dom-helpers isn't getting installed via yarn because it's in devDependencies. 

Should this library be included in dependencies so that users of the test helpers don't have to install the library manually? Or am I including `clickTrigger` incorrectly?

**Comment by cibernox** [comment]
That makes total sense. Could you PR? I not on a computer but I can merge things from mobike

**Comment by paulcwatts** [comment]
Filed https://github.com/cibernox/ember-basic-dropdown/pull/232
