### ISSUE TITLE
Adding hide/show actions 

### ISSUE THREAD

**Issue by karellm** [cibernox/ember-basic-dropdown#242]
Hey,

I have a edge case (so it is totally fine if you don't want that in here). My dropdown is composed of buttons that trigger a confirm modal. I use `ember-modal-dialog`. The issue is that when I click the button inside the dropdown, I want to open the modal and hide the dropdown. I can't use `dropdown.actions.close` because it destroys the dropwdown and my modal at the same time. So I was wondering if you could had a `show` and a `hide` action that would keep the dropdown in the DOM while making it invisible.

UPDATE: it is actually trickier than what I describe because any click outside the modal will cause it to close 😕 . Any idea how to work around that?

Thanks!

**Comment by cibernox** [comment]
> I can't use dropdown.actions.close because it destroys the dropdown and my modal at the same time

Why does closing the dropdown also destroy the modal? I don't see the relation.

As of preventing the dropdown to close, you can pass an `onclose=(action "myAction")` and as all actions it receives the event that triggered as last argument. You can check `e.target` to see if you are clicking the modal overlay and `return false`, so the dropdown doesn't close.

**Comment by karellm** [comment]
It is destroying the modal because the button in the dropdown is a component. The component has both the button and the modal (with `ember-wormhole` it is then placed somewhere else in the dom). 

I realize it is starting to get very specific to my use case. I would need a way to "freeze" the modal (prevent actions) and to "hide" it. Then once the modal closes, "defreeze" and "show". I would totally understand if you don't want to add this! In the meantime I will playing with your suggestion.

**Comment by cibernox** [comment]
If the modal is outside the dropdown, even if you close the dropdown it should stay open, correct?

```hbs
{{#basic-dropdown as |dd|}}
  {{#dd.trigger}}{{/dd.trigger}}
  {{#dd.content}}
    <button onclick={{action (mut modalIsOpened) (not modalIsOpened)}}>Open Modal</button>
  {{/dd.content}}
{{/basic-dropdown}}

{{#if modalIsOpened}}
  {{#ember-wormhole to="modal-placeholder"}}
    Content of the modal
  {{/ember-wormhole}}
{{/if}}
```

**Comment by karellm** [comment]
I think it would work (will test) but I like the idea of keeping composability and everything in components where it belongs. I will definitely move it out if I can't figure a clean solution to my issue.

**Comment by karellm** [comment]
@cibernox I liked the idea of having a component with a modal per action in the dropdown (the code architecture was cleaner) but since all the dialogs are very alike, I ended up doing what you suggested and move the dialog out of the dropdown.

Thanks for the great support as always!
