### ISSUE TITLE
MutationObserver issue around transition to or from route with ember-basic-dropdown

### ISSUE THREAD

**Issue by dehuszar** [cibernox/ember-basic-dropdown#250]
I am seeing this issue in v0.31.0-beta.1 via ember-power-select v1.6.0-beta.0 in Ember 2.10.

The routes I am switching between both return an RSVP.hash of 2-3 model types.  I switched the queries for one model type in both hashes to a return peekAll request but then gets it's contents refreshed by a query in the background.

Since that change I now get a MutationObserver error similar to the one from this issue (https://github.com/cibernox/ember-basic-dropdown/issues/33) when I transition into and out of the route containing a basic-dropdown.  Transitioning into the route, it reads (when evaluating ember-basic-dropdown/components/basic-dropdown/content.js):
```
Uncaught TypeError: Cannot read property 'MutationObserver' of undefined
    at Module.callback (content.js:7)
    at Module.exports (loader.js:123)
    at Module.reify (loader.js:144)
    at Module.exports (loader.js:121)
    at requireModule (loader.js:23)
    at Class._extractDefaultExport (resolver.js:368)
    at Class.resolveOther (resolver.js:81)
    at Class.superWrapper [as resolveOther] (ember.debug.js:39641)
    at Class.resolve (ember.debug.js:5050)
    at resolve (ember.debug.js:2445)
```
The statement on line 7 reads:
```
var MutObserver = self.window.MutationObserver || self.window.WebKitMutationObserver;
```
Here, self refers to one of the component instances on the page.  Each component instance gets each model array from the hash, including the model that is peek'd, passed into it.  One of those models in the array is used to populate the dropdown list on the page being transitioned into.

When I transition away from the route containing the dropdowns I see this (in /ember-basic-dropdown/components/basic-dropdown/trigger.js):
```
trigger.js:46 Uncaught TypeError: Cannot read property 'body' of undefined
    at Class.willDestroyElement (trigger.js:46)
    at Class.superWrapper [as willDestroyElement] (ember.debug.js:39641)
    at Class.trigger (ember.debug.js:41457)
    at Class.superWrapper [as trigger] (ember.debug.js:39641)
    at ComponentStateBucket.destroy (ember.debug.js:12005)
    at UpdatableBlockTracker.destroy (ember.debug.js:45050)
    at SimpleBlockTracker.destroy (ember.debug.js:45050)
    at SimpleBlockTracker.destroy (ember.debug.js:45050)
    at SimpleBlockTracker.destroy (ember.debug.js:45050)
    at UpdatableBlockTracker.destroy (ember.debug.js:45050)
```
the statement in question: 
```
self.document.body.removeEventListener('touchmove', this._touchMoveHandler);
```
The model array used to populate the dropdown options on the first page is used to populate the primary content space on the second page, and while it is not the set of records that has been switched to the peekAll request method, the results of that peekAll request gets passed into the components populated by the model array used in the dropdowns, and I think that's where things are breaking down.

If I refresh the page with the dropdowns by itself, the page loads fine as do the dropdowns.  If I comment out the dropdowns, the page transitions without issue.

Any thoughts on what might be happening here?  Thanks in advance.

**Comment by cibernox** [comment]
I'll read it more carefully later. Just to be clear, this happens even if the dropdowns are closed?

**Comment by dehuszar** [comment]
Correct.  If I load the page with dropdowns directly, it loads fine.  Without any other interaction, if I transition away I get the latter error.  If I then refresh the page I transitioned to and then transition back into the original page with the dropdowns I get the first error.

**Comment by dehuszar** [comment]
@cibernox if you haven't taken a look at this, don't just yet.  I may have identified the issue and it may be unrelated to this addon, the addon is just the where the underlying issue manifests.  I'll have more time to review on Monday.  If you _have_ spent time on it, let me PayPal you a beer or something if it turns out that I sent you on a red herring.

**Comment by cibernox** [comment]
@dehuszar No, I didn't check this at all 👍 . 
For cleanness I'm going to close this and you can open if needed.

**Comment by kmsnell** [comment]
@dehuszar I am seeing this same issue in an application I am working on. Did you figure out what was causing it?

**Comment by cibernox** [comment]
@kmsnell If you share produce a reproduction example that would be great.

**Comment by kmsnell** [comment]
@cibernox I am using the ember-paper addon and using their {{paper-menu}} component which creates a dropdown using the ember-basic-dropdown component. When I create a {{paper-menu}} on one route (say /calendar) and then transition to another route (say /products/1) the transition fails and I see these errors in my console:

![image](https://cloud.githubusercontent.com/assets/5169346/25198245/bc012744-24fb-11e7-91ab-d437b2305a03.png)

If you think it might be an issue with the ember-paper addon I will follow up with them, but it seems like these errors are being generated from the ember-basic-dropdown addon at first glance.

Thank you! 

FYI versions I am using:
ember-basic-dropdown: latest
ember-cli: 2.11
ember-paper: 1.0.0-alpha.18

**Comment by cibernox** [comment]
Perhaps. I don't see any reason why `self.window` would be undefined 🤔

**Comment by dehuszar** [comment]
@kmsnell For me it just stopped happening after some related changes, but I never identified the exact interaction at fault.  I _believe_ I had something to do with two separate operations attempting to update a the same value, one being a computed value, and the other being a set fired from elsewhere on the controller.
