### ISSUE TITLE
horizontalPosition is ignored when you renderInPlace

### ISSUE THREAD

**Issue by SirZach** [cibernox/ember-basic-dropdown#255]
setting `renderInPlace=true` and `horizontalPosition='right'` doesn't seem to put the content right-aligned but if `renderInPlace` is false then it is correctly aligned.

**Comment by nmcclay** [comment]
👍

**Comment by cibernox** [comment]
I missed this back in the day. Yes, that is a known limitation. I'll label this as an enhancement but I don't think I'll have time to do it soon. However I think it should be a fairly simple CSS thing.

**Comment by graemechapman** [comment]
Horizontal positioning of `auto-right` also doesn't work correctly with `renderInPlace`

@cibernox are you happy to accept a PR to fix this issue?

**Comment by billdami** [comment]
@graemechapman would love to see this fixed as well. 

It seems the culprit is that the `ember-basic-dropdown-content--right` is not being applied to the dropdown content element. which would give the needed `right: 0;` style.

**Comment by graemechapman** [comment]
@billdami indeed, the calculatePosition method does not account for `right` or `auto-right` positioning at all currently when renderInPlace is set. I have worked around this for now with a custom calculatePosition, I'll put in a PR with a fix when I get a chance.

**Comment by billdami** [comment]
@graemechapman ok awesome. would you mind sharing your custom calculatePosition() method here?

**Comment by graemechapman** [comment]
@billdami for a very basic implementation (assuming you only want `auto-right`) you could do something like this...

```js
calculatePosition(trigger, content) {
  const triggerRect = trigger.getBoundingClientRect();
  const dropdownRect = content.getBoundingClientRect();

  return {
    horizontalPosition: triggerRect.right > dropdownRect.width ? 'right' : 'left',
    verticalPosition: 'below'
  }
}
```

For anything more advanced you will need to extend the [calculateInPlacePosition](https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/utils/calculate-position.js#L143) util.
