### ISSUE TITLE
Add `handleRootMouseDown` to <html>, not <body>

### ISSUE THREAD

**Issue by cibernox** [cibernox/ember-basic-dropdown#258]
I think that this could prevent the pitfall of the dropdown not closing because the body is not full height.

**Comment by dennismende** [comment]
What do you mean with add to <html>?

Currently we see a lot of errors with handleRootMouseDown and I would like to fix this asap.

Thanks

**Comment by cibernox** [comment]
@dennismende I don't expect you to have any error. The only caveat is that sometimes the body is smaller than the body, some areas of the screen below the last element don't close the dropdown. But it shouldn't throw any error.

**Comment by dennismende** [comment]
Currently we see the following error after each click when we changed a value in a dropdown: `Cannot read property 'contains' of null` from the function `handleRootMouseDown`.

We are trying to understand this problem since a few day but we don't find the solution for it.

**Comment by cibernox** [comment]
@dennismende version of the addon and the browser?

**Comment by dennismende** [comment]
We are using power-select 1.8.2 and Chrome 58 or Firefox 53.

In addition we also use power-select-with-create 0.4.3

**Comment by cibernox** [comment]
Could you create a reproduction? I don't recall anyone reporting this error in recent times.

**Comment by dennismende** [comment]
I forgot one important information. It only happens after a build. I will try to create a sample.

**Comment by cibernox** [comment]
What do you mean with "after a build"? That it only happens in production?

**Comment by dennismende** [comment]
Yes an EmberJS build to production.
