### ISSUE TITLE
Cannot handle scrolling that is not on the window

### ISSUE THREAD

**Issue by RustyToms** [cibernox/ember-basic-dropdown#267]
If the dropdown is inside an element that is scrollable the event listeners will not pick up the scroll event. It would be great if the user could pass [a string containing one or more CSS selectors separated by commas](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll) which would then be added to the global listeners for the `scroll` event.

![non-scrolling_dropdown](https://cloud.githubusercontent.com/assets/5260472/25151121/958d53e0-2441-11e7-8c97-ff30b8ed1733.gif)

**Comment by cibernox** [comment]
I believe this can be closed
