### ISSUE TITLE
The position is not calculated properly when the dropdown is attached somewhere other than the body

### ISSUE THREAD

**Issue by RustyToms** [cibernox/ember-basic-dropdown#270]
This dropdown was placed in an element that was a child of the scrolling element so that it would scroll with the content. But the position was off because there was padding and margin not taken into account, and the viewportWidth was different. The positioning method assumes that the dropdown content is placed in the body element.

```hbs
<div class="scrollable-container">
  <div id="basic-dropdown-target-inside-scrollable-container">
  <!-- Blah blah blah content -->
    {{#basic-dropdown horizontalPosition="right" as |dropdown|}}
      {{#dropdown.trigger}}Click me{{/dropdown.trigger}}
      {{#dropdown.content to="basic-dropdown-target-inside-scrollable-container"}}
         ...
      {{/dropdown.content}}
    {{/basic-dropdown}}
  </div>
</div>
```

![position dropdown inside scroll parent](https://cloud.githubusercontent.com/assets/5260472/25156156/28a9bdf8-2456-11e7-8443-752987b52971.gif)

**Comment by cibernox** [comment]
I believe this can be closed.
