### ISSUE TITLE
I cannot load the dummy app without the Babel polyfill

### ISSUE THREAD

**Issue by RustyToms** [cibernox/ember-basic-dropdown#274]
I can build the app but when I served it to http://localhost:4200/ nothing was shown, and the dev console just reported a single error `regeneratorRuntime is not defined`. I found out this is because Babel requires a polyfill. Perhaps this works for people if they have this polyfill globally installed?

**Comment by cibernox** [comment]
I fixed that like 1h ago. Rebase over master :)
