### ISSUE TITLE
Inquiry: Generic nesting logic

### ISSUE THREAD

**Issue by alexander-alvarez** [cibernox/ember-basic-dropdown#286]
Relates to: 
https://github.com/cibernox/ember-basic-dropdown/commit/fb664b012c9c21cc8a0e56fadd3efb1c023e2a67 -> https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components/basic-dropdown/content.js#L178
UI best practices aside, how could we make this more generic so that we could have 3 dropdowns?

maybe some sort of `groupId` that gets generated?

```htmlbars
{{#basic-dropdown as |dd|}}
  {{#dd.trigger}}
   click
  {{/dd.trigger}}
  {{#dd.content}}
    {{#basic-dropdown groupId=dd.groupId as |ndd|}}
  {{#ndd.trigger}}
   click 2
  {{/ndd.trigger}}
  {{#ndd.content}}
   ...etc
  {{/ndd.content}}
{{/basic-dropdown}}   
  {{/dd.content}}
{{/basic-dropdown}}

```

or a recursive call like
```js
function dropdownIsValidParent(el, dropdownId) {
  let closestDropdown = closestContent(el);
  if (closestDropdown) {
    let trigger = document.querySelector(`[aria-owns=${closestDropdown.attributes.id.value}]`);
    let parentDropdown = closestContent(trigger);
    return parentDropdown && parentDropdown.attributes.id.value === dropdownId || dropdownIsValidParent(parentDropdown, dropdownId);
  } else {
    return false;
  }
}
```

**Comment by cibernox** [comment]
A recursive call sounds reasonable to me. I should work with any level of nesting.

I'd take a PR with that feature. 
I'd start with an example in the dummy app in the `/legacy-demo` route. I have all sort of stuff there for playing with it.

**Comment by alexander-alvarez** [comment]
I'll throw it together

**Comment by alexander-alvarez** [comment]
turns out the little snippet I made works...
https://github.com/cibernox/ember-basic-dropdown/compare/master...alexander-alvarez:infinite-nesting

Can I write tests against the `/legacy-demo` page / or where do you want tests?

**Comment by cibernox** [comment]
The /legacy-demo is just for me to play, I change them all the time, you should use an integration test.
