### ISSUE TITLE
Feature request: Horizontal alignment

### ISSUE THREAD

**Issue by ssured** [cibernox/ember-basic-dropdown#29]
It would be very nice if there was a possibility to influence the horizontal placement.

Right when you create a dropdown on the far right side, it will be pushed against the right border of the window:
![image](https://cloud.githubusercontent.com/assets/2558804/11669313/5700a20c-9dfc-11e5-813e-326043b755d9.png)

When setting the CSS position with `right` instead of `left`, the result is nicer:
![image](https://cloud.githubusercontent.com/assets/2558804/11669402/cea5ea60-9dfc-11e5-9129-b26a32b1fe02.png)

Is this on the component roadmap? Thanks for the nice lib!

**Comment by cibernox** [comment]
It wasn't, but it makes a lot of sense.

As of today this component accepts on argument to control the position, `dropdownPosition`. The accepted values for that property are not `auto` (the default), `above` and `below`. 

This could be extended to support other values. Values could be `top-left`, `top-right`, `bottom-left`, `bottom-right` and `auto`. Auto should also be smarter and when the space on the right is too small.

Added to the backlog.

**Comment by cibernox** [comment]
@ssured There is horizontal alignment capabilities in the latest version of the addon. Check if it works for you :grinning:
