### ISSUE TITLE
How to programmatically open dropdown

### ISSUE THREAD

**Issue by Calanthe** [cibernox/ember-basic-dropdown#295]
Hi there,

I am building a date-picker component which combines `ember-basic-dropdown` and `ember-power-calendar`. I am working on a feature that after selecting a date on one date-picker (`dateFrom`), another one (`dateTo`) automatically opens. I wanted to trigger a jQuery `mousedown` event on the `.ember-basic-dropdown-trigger` DOM element but this does not work because it's not a native event. I am aware of the existence of `https://github.com/cibernox/ember-native-dom-helpers` but it can be used only for testing.

So far I implemented the `mousedown` event using `new MouseEvent()` and a proper polyfill. But is there another, better way to programmatically open dropdown?

**Comment by cibernox** [comment]
Did you check https://github.com/cibernox/ember-power-datepicker
It is essentially what you describe. If you still want to build your own I'll answer the question 😄

**Comment by Calanthe** [comment]
Hi cibernox,

Yes, I discovered the `ember-power-datepicker` lately but for now my team decided to stay with `ember-basic-dropdown` and `ember-power-calendar`. 

The `ember-basic-dropdown` has an `open()` action defined in API but the problem is that I don't have access to the `dropdown` object inside another `dropdown` object. Or maybe I do have, just don't know how to do that. So yes, please answer my question.

**Comment by cibernox** [comment]
The is two ways of opening the dropdown.

- The Firing an event is simple enough as it just requires to trigger a mousedown on the trigger, which is just what you described: `triggerElement.dispatchEvent(new MouseEvent('mousedown'))`.
If that works I wouldn't worry changing it.
- Another option is using the `registerAPI` action of the dropdown. That option is called whenever the component updates its state, including when it's first rendered. You can store that object and use it as a remote control of the dropdown.

```hbs
{{#basic-dropdown registerAPI=(action (mut remoteController)) as |dd|}}
  ....
{{/basic-dropdown}}
```

Then in your code you can `this.get('remoteController').actions.open()`. However take into account that grabbing a reference to this object in an object that is not garbage collected (like controllers or services that never get destroyed) can prevent the dropdown from being garbage-collected. If you grab a reference to the API of the dropdown in an object that is never destroyed you should nullify that reference when you don't want it anymore.

**Comment by Calanthe** [comment]
I think that I will stay with the `MouseEvent('mousedown')` solution, but knowing about the `registerAPI` action may be useful some other day.

Thank you for your fast response!

**Comment by cibernox** [comment]
You're welcome
