### ISSUE TITLE
Animation doesn't work with custom position

### ISSUE THREAD

**Issue by okachynskyy** [cibernox/ember-basic-dropdown#300]
1) Add `calculatePosition` function from 
https://www.ember-basic-dropdown.com/docs/custom-position
2) Then add animation from
https://www.ember-basic-dropdown.com/docs/animations
3) Animation doesn't work. 
If I remove `calculatePosition=calculatePosition` from template - animation works.

**Comment by rennomarcus** [comment]
Hi, I was having the same problem. I didn't need something fancy and I was still going through the documentation. If you don't need anything complex either, you can just use some properties such as horizontalPosition, verticalPosition, renderInPlace or matchTriggerWidth. 
For me it setting to verticalPosition="below" was enough. The default behavior is to use "auto" which selects what it thinks it's the best for your screen. More info here: https://www.ember-basic-dropdown.com/docs/position

**Comment by cibernox** [comment]
I missed this last week. I'll try to check, but I'd swear I had that working.

**Comment by okachynskyy** [comment]
@cibernox ping :)

**Comment by billdami** [comment]
Noticing this issue as well, but not when setting a custom `calculatePosition` function, its when using `renderInPlace=true` and `horiziontalPosition="center"`. If I remove just the `renderInPlace=true`, animations work correctly.

**Comment by cibernox** [comment]
Noted. I'm a bit booked but I will fix another issue this week and this one might be related.

**Comment by cibernox** [comment]
I believe I've just fixed this and released in 0.33.3

Let me know if it's not the case.

**Comment by billdami** [comment]
@cibernox doesn't appear to have fixed it, in my case at least. Note that the only property on `{{basic-dropdown}}` that I'm changing is setting `renderInPlace=true`.

I can try creating a more isolated example in a twiddle or something if you want, in case there is maybe another application-related cause here.

**Comment by cibernox** [comment]
@billdami I've released yet another version. On my tests the animation was working but the horizontalPosition was being ignored, which means that the dropdown was anchored to the left. Now it is positioned properly on my test.

**Comment by billdami** [comment]
@cibernox hmm no change in my app with v0.33.4. I created a twiddle to try to demonstrate, and while its not exactly what I'm experiencing, it weirdly looks like animations will now only work when `renderInPlace=true`, instead of the other way around :-D however I could have something misconfigured here:

https://ember-twiddle.com/a05eaa90e2f0a448264d7b30b66c24b3?openFiles=templates.application.hbs%2C

**Comment by cibernox** [comment]
@billdami they both work properly once you fix the error in the console: https://ember-twiddle.com/eb762a92969d22d94260de4dd5e05373?openFiles=templates.application.hbs%2C

**Comment by billdami** [comment]
Ah yeah, my bad :X So this seems to be an application-specific issue then, I'll keep digging. Thanks!

**Comment by cibernox** [comment]
@billdami There was two legitimate problems that I've fixed, but now that they are fixed it is possible to animate dropdowns that are rendered in placed.

**Comment by billdami** [comment]
@cibernox yeah must've just been a bad build or something on my end, everything looks good now. Many thanks!!
