### ISSUE TITLE
Let developers specify how many options are shown on click

### ISSUE THREAD

**Issue by jeffrey008** [cibernox/ember-basic-dropdown#303]
It would be nice to pass an option to determine how many options are shown. Similar to `size` attribute on `<select>`.

Current I have to hack the `.ember-power-select-options[role="listbox"]` class and set `max-height: 99999999em` to let EPS to show all options on click.

Is that feature already exist out of the box or do we need to add feature by ourself? Thanks.

**Comment by cibernox** [comment]
This does not belong to this repo. Closing. Feel free to reopen in ember-power-select.
