### ISSUE TITLE
Trigger breaks on IE9

### ISSUE THREAD

**Issue by Nikash** [cibernox/ember-basic-dropdown#304]
Clicking on the trigger breaks in IE9 apparently due to the use of `classList` in (`trigger.js#init` & `trigger.js#stopTextSelectionUntilMouseup`) which is only supported in IE 10 and up.

The fix is to apparently just use jQuery's `addClass` and `removeClass` methods instead which handles the browser support.

**Comment by cibernox** [comment]
This addon does not support IE9. It only supports IE10 and beyond.

**Comment by Nikash** [comment]
Oh, I was misled by the IE 9 mention in the [Intelligent and customizable positioning](https://github.com/cibernox/ember-basic-dropdown#intelligent-and-customizable-positioning) section.
