### ISSUE TITLE
No collision detection when horizontalPosition is specified

### ISSUE THREAD

**Issue by dossorio** [cibernox/ember-basic-dropdown#312]
We come across an issue today, where collision detection would not kick in if you specified a `horizontalPosition`.

By default, if you don't specify `horizontalPosition`, collision detection kicks in and keeps the content of the dropdown inside the viewport:

![default-horizontal-position](https://user-images.githubusercontent.com/4788852/27740769-ee28cabe-5daa-11e7-8111-9376f1093abe.gif)

Then if you specify a horizontalPosition, `horizontalPosition="right"` for example, collision detection doesn't kick in, and the content of one of the dropdowns doesn't fit in the viewport:

![specifying-horizontal-position](https://user-images.githubusercontent.com/4788852/27740777-f3f3f37e-5daa-11e7-9d96-8b39a3002de3.gif)

Here you have a repo to illustrate the problem https://github.com/dossorio/ebd-collision-detection

Is there anyway we can achieve like a `left-auto` / `right-auto` behaviour ? 
It might be related to #168 

Many thanks @cibernox !!

**Comment by cibernox** [comment]
Actually that is a good point. At the moment, `right` means "unconditionally-right". I'd accept an "auto-right" that behaves like "auto" but prefers to anchor to the right.

**Comment by cibernox** [comment]
I'm a bit short of time lately, but I'll try to give it a spike to see if it's a 15 minutes thing. If it's not, I'll call for help.

**Comment by catchamonkey** [comment]
Thanks for this @cibernox, and thanks even more for adding it for us so quickly!

👍
