### ISSUE TITLE
Is there any way to create a sub-menu with this basic-dropdown?

### ISSUE THREAD

**Issue by lesyk-lesyk** [cibernox/ember-basic-dropdown#317]
For example:
![submenu](https://user-images.githubusercontent.com/16646570/27855823-93ad4b82-6174-11e7-9053-fb5178a508b0.png)

**Comment by cibernox** [comment]
I'm in the middle of a moving so I'll have 0 time until next week. Please ping me again if I haven't responded by next Wednesday.

Sorry by the huge delay, moving between countries can be madness.

**Comment by okachynskyy** [comment]
@cibernox, okay, no problem
Have a nice trip ;)

**Comment by gwak** [comment]
Hi, I'm currently having the same requirement, where I'm simply trying to have a datepicker (with ember-power-calendar within a dropdown) in a dropdown.
As soon as I click on a day the parent dropdown looses focus and close, causing the datepicker to be destroy before even registering the selected date.

**Comment by okachynskyy** [comment]
@cibernox, ping :)

**Comment by vincentcapicotto** [comment]
Hi, 

I need the same thing.

So, @cibernox, ping too :)

**Comment by jameshahn2** [comment]
@vincentcapicotto Here you go. https://ember-twiddle.com/0ba02dd857eccbb3c642c4b1421887ff?openFiles=templates.application.hbs%2C

**Comment by vincentcapicotto** [comment]
@jameshahn2 , oh thank you I will try it ;)
