### ISSUE TITLE
Yarn.lock unresolvable dependencies

### ISSUE THREAD

**Issue by jrowlingson** [cibernox/ember-basic-dropdown#318]
It appears that a [few](https://github.com/cibernox/ember-basic-dropdown/pull/315/files#diff-8ee2343978836a779dc9f8d6b794c3b2R676) of the resolved dependencies in the `yarn.lock` are unavailable (its not clear to me if this is a private npm registry or not). After cloning the repo and running `yarn` I am now seeing the following error:

```
error An unexpected error occurred: "https://artifacts.apple.com/api/npm/npm-amp/ember-cli-babel/-/ember-cli-babel-6.5.0.tgz: getaddrinfo ENOTFOUND artifacts.apple.com artifacts.apple.com:443".
```

Related https://github.com/cibernox/ember-basic-dropdown/pull/315

**Comment by cibernox** [comment]
@jrowlingson #319 should have fixed this.
