### ISSUE TITLE
Stopping Event Propagation 

### ISSUE THREAD

**Issue by tobias-g** [cibernox/ember-basic-dropdown#320]
Is there a way to stop event propagation when clicking the trigger similar to how it can be stopped with actions using `bubbles=false` such as below?

```
<a href="some_url">
My link
<button {{action 'showDetails' bubbles=false}}>Extra Info</button>
</a>
```
I have a link with lots of content and want one part of that content is to be a dropdown (or clickable tooltip) that when clicked only shows the dropdown content and does not trigger the link.

**Comment by kaermorchen** [comment]
I catch this issue too. When I have a parent component with dropdown inside 

```
{{#some-component-with-click-event}}
  {{!-- some html --}}
  {{#basic-dropdown as |dropdown|}}
    {{#dropdown.trigger}}Click{{/dropdown.trigger}} {{!-- some-component-with-click-event should't catch this click, but how?  --}}
      {{#dropdown.content}}
      {{/dropdown.content}}
    {{/basic-dropdown}}
{{/some-component-with-click-event}}
```

**Comment by cibernox** [comment]
This component, for reasons too long to explain here, doesn't open on click, it opens/closes with `mousedown`. You can use `onOpen(dropdown, event)`/`onClose(dropdown, event)` to do whatever you want with the event.

Aternatively you can wrap the trigger in a div with an event handler that prevents the propagation:
```
<div onclick={{action "stopPropagationOfEvent"}}>
  {{#basic-dropdown ...}}
</div>
```

**Comment by cibernox** [comment]
Actually I would like to improve the component so the user can decide wether it opens with click or with mousedown, but I don't want to guarantee an time frame.

**Comment by cibernox** [comment]
FWIW, I decided that it was time to tackle that. Now the component can open/close with click events instead of mousedown, but the user must explicitly choose that.

```
{{#basic-dropdown as |dd|}}
  {{#dd.trigger eventType="click"}}Click me{{/dd.trigger}}
  {{#dd.content}}Content{{/dd.content}}
{{/basic-dropdown}}
```

**Comment by cibernox** [comment]
I believe this can be closed now.
