### ISSUE TITLE
Unable to get property 'removeEventListenter' of undefined or null reference

### ISSUE THREAD

**Issue by MattNguyen** [cibernox/ember-basic-dropdown#33]
Browser: IE10

In `willDestroy` when `MutObserver` is `undefined`, `removeGlobalEvents` is called, which attempts to grab the selector `.ember-basic-dropdown-content` (https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components/basic-dropdown.js#L181).

This causes the aforementioned error to be raised since `.ember-basic-dropdown-content` has already been removed from the DOM.

Does `removeGlobalEvents` even need to be called? Unless I'm mistaken, it seems like the events are added only when toggling the dropdown. Do you have any suggestions?

**Comment by cibernox** [comment]
I suspect that this is not a problem anymore since 0.8. Can you check?

**Comment by MattNguyen** [comment]
@cibernox - Still getting this error.

**Comment by cibernox** [comment]
Ok, I've just been able to reproduce it with ei11 running in IE10 mode. I'll try to tackle it tomorrow.

**Comment by cibernox** [comment]
It was simpler than it seemed at first. 

Fixed in 0.8.5
