### ISSUE TITLE
Acceptance test helper compatibility with eslint rule `no-undef`

### ISSUE THREAD

**Issue by caseywatts** [cibernox/ember-basic-dropdown#339]
Since `registerBasicDropdownHelpers();` globally injects the test helpers, eslint isn't aware that they are actually defined. The eslint rule `no-undef` gets triggered (in my app, as an `error`).

I can think of some options:

- manual workaround: declare the global in each test file individually (my first idea which made me not wanna use the helpers even lol)
- in the `.eslintrc.js` for the entire tests/folder. The `ember install` for this could add it to `tests/.eslintrc.js` like (I believe) [ember-sortable](https://github.com/jgwhite/ember-sortable) does
- Somehow the Ember native helpers like `click()` manage to let eslint know that these are defined in acceptance test files, but not in integration tests or application code. That sounds ideal, but I'm not sure how to even figure out how Ember core helpers do that?
- we could offer a manual import in each file that needs these helpers? Actually, we probably can't do that because it has to be registered as part of the acceptance test helpers' promise chain, huh. (update! maybe this is my fav - see below)

**Comment by caseywatts** [comment]
ohh interesting:
https://github.com/DockYard/eslint-plugin-ember-suave/issues/46

**Comment by caseywatts** [comment]
I think my favorite option so far is what's described in that issue ^
- Manually import the helper in each acceptance test that needs it, and have the import call `registerAsyncHelper` for us~

**Comment by cibernox** [comment]
Actually, although I haven't advertised it because I didn't migrate all helpers, you can also just import them and use them, they don't need to be registered anywhere:

```js
import { clickTrigger } from 'ember-basic-dropdown/test-support/helpers';
```

And the good thing of this is that they work in both acceptance and integration.
