### ISSUE TITLE
Open by default?

### ISSUE THREAD

**Issue by eric-adstage** [cibernox/ember-basic-dropdown#344]
Hi,

How can I set the options list to be open by default? If that's not easy/not possible, how can I have an action from a parent component trigger the dropdown to open?

Background: I have extended the dropdown to have a "filter" input component, and on keypress I have the pressed key's value being sent to the filter box as input, which works, but it can't be seen until the user clicks the dropdown trigger to toggle it open. I'd love to open the dropdown programmatically once that first key is pressed to show the list of options filtered by that first keystroke, without the user having to click the trigger to open the dropdown. Possible?

**Comment by cibernox** [comment]
@eric-adstage Check the `initiallyOpened` in https://www.ember-basic-dropdown.com/docs/api-reference

Bear in mind that this works for rendering the component in an open state, but does not prevent it from being closed. If you want it to remain open, you should define an `onClose` action that returns `false`, which prevents the dropdown from closing.
