### ISSUE TITLE
this context is missing in calculatePosition handler

### ISSUE THREAD

**Issue by mehulkar** [cibernox/ember-basic-dropdown#354]
It looks like `this` is `undefined` in `calculatePosition`. Not sure if I'm doing something wrong or if there's another way to get the context. Filing this issue while I investigate more / workarounds. 

Demo: https://github.com/mehulkar/ebd-this/commit/0326ccdc0894a635363b845a38af6cef9a7e3a5f

**Comment by cibernox** [comment]
@mehulkar This was a change? For what I can remember, that was always what way. 
The signature (`calculatePosition(trigger, content, destination, { previousHorizontalPosition, horizontalPosition, previousVerticalPosition, verticalPosition, matchTriggerWidth })`) intentionally restricts the information you have access to. Giving access to `this` might make people rely on things that are not publicAPI.

**Comment by mehulkar** [comment]
@cibernox no, not a change. I just used `calculatePosition` in a component and wanted to access a component property and found that I could not do it. It's possible this is a case of "don't do that" though. In that case, feel free to close this :)
