### ISSUE TITLE
dropdown_content fills screen

### ISSUE THREAD

**Issue by schlesingermatthias** [cibernox/ember-basic-dropdown#360]
Hi again, 

I specified a height of 100% to both `<html>`, `<body>` and `<ember-view> `but now the dropdown_content expands to fill the screen as well...What can I do about that?

Update: The problem only occurs if I set the 100% on the ember-view class. It works if I add the 100% height to the first div (which has class ember-view) like that: 
`body { > div:first-of-type {
    height: 100%;
  }}`

Is that a bug in ember or the dropdown?

Thanks

**Comment by cibernox** [comment]
None really. All ember components have the ember-view class added automatically. It's everywhere. You should put styles on it.
