### ISSUE TITLE
Option to Prevent Event Propagation

### ISSUE THREAD

**Issue by zamoore** [cibernox/ember-basic-dropdown#382]
I'm rendering the dropdown inside a table row which has an action bound to the click event. Toggling the dropdown also triggers the action on the table row due to bubbling.

Would you be open to a PR to add an option to stop event propagation?

**Comment by cibernox** [comment]
I'd suggest wrapping the component in a div or something with an event hander.
`<div onclick={{action "stopTheProp"}}>{{eps...}}</div>`

I think that there is no point in adding an API to stop the propagation of events, and it will be complicated to come up with one flexible to stop the propagation things other than click, like mousedowns, mouseover etc...)
