### ISSUE TITLE
Support for rfc232/rfc268 tests?

### ISSUE THREAD

**Issue by chbonser** [cibernox/ember-basic-dropdown#384]
Helper registration has changed in the new rfc232/rfc268 style tests. Are there plans for supporting the rfc232/rfc268 style tests?

**Comment by cibernox** [comment]
It is already supported. You just have to import whatever helper you want from `ember-basic-dropdown/test-support/helpers`, although I plan to make the import path nicer, to: `ember-basic-dropdown/test-support`
