### ISSUE TITLE
Is there a way to make the content scrollable

### ISSUE THREAD

**Issue by Ronald-Gynzy** [cibernox/ember-basic-dropdown#385]
I have a lot of items inside the content. Via `calculatePosition` i calculate the new position and if i find out that the dropdown menu (content) does not fit inside the viewport, i want to add a `overflow-y: 'scroll'`, so the menu always remains inside the viewport, but the content inside the menu is scrollable. Is there a way to do this?

**Comment by Ronald-Gynzy** [comment]
found another way to do it

**Comment by emilkarl** [comment]
> found another way to do it

What is that other way?
