### ISSUE TITLE
'isOpen' property does not work as expected.

### ISSUE THREAD

**Issue by Ronald-Gynzy** [cibernox/ember-basic-dropdown#389]
For my dropdown, i want the content to open with the selected item on top of the menu. Therefore i need to know the `offsetTop` of the div (`overflow: scroll`)  inside the content. Via jQuery i grab the the 'selectedItem' from the content, but the wormhole with the content is not visible yet when the `onOpen` event is triggered.
```
actions: {
  onOpen(dropdown) {
    // content not visible yet
  }
}
```

inside `dropdown` there is a variable called `isOpen` which is:
> // Truthy if the component is currently opened (https://ember-basic-dropdown.com/docs/api-reference)

So i decided to store`dropdown` and add a observer on the `isOpen` property.
```
actions: {
  onOpen(dropdown) {
    // content not visible yet
     this.set('_dropdown', dropdown);
  }
}

_calculations: observer('_dropdown', '_dropdown.{isOpen}', function() {
  const content = $('.dropdown__basic-content');
  debugger; // _calculations() won't trigger, isOpen never changes.
});
```
Problem i got now, the observer never get triggered. So I've been digging through the documentation and i found out the `registerAPI` action. I changed the the code into this.

```
actions: {
  registerAPI(dropdown) {
    if(dropdown.isOpen === true) {
      const content = $('.dropdown__basic-content');
      debugger; // Still no content visible in the DOM.
    }
  }
}
```
Still nothing visible in the DOM. Is this a bug?

**Comment by cibernox** [comment]
No, it's not. When the property `isOpen` changes, the component opens, but rendering takes time (at least 1 frame), so to ensure the rendering happened you have to use:
`Ember.run.schedule('afterRender', function(){ /* in here the DOM is already updated*/ })`
