### ISSUE TITLE
Older Version of Basic Dropdown

### ISSUE THREAD

**Issue by hadiwina** [cibernox/ember-basic-dropdown#393]
I'm really interested to use this addon for some new features that I need to implement. Unfortunately, the current app that I'm implementing these features on are still on 1.13. Upgrades are still in the work but I need to start implementing this feature for business reasons.

It seems that even for the pre 1.0.0 version of this add on, version 0.34 is still for Ember 2.4+. Was wondering if there's an easy way for me to find out which version that still supports Ember 1.13 from the releases that you have?

Thanks!

**Comment by cibernox** [comment]
There was a _very_ early version that supported 1.13, but it is pretty ancient and the API was quite different. But if you need to start use it, the last version that supported 1.13 I believe that was v0.11.7

**Comment by hadiwina** [comment]
Thanks! Will check it out! Much appreciated!
