### ISSUE TITLE
Cannot read property 'id' of null (destination)

### ISSUE THREAD

**Issue by cameronblandford** [cibernox/ember-basic-dropdown#407]
Hey there - when running in a test environment, this bit of code is run to find the right destination:
```
     _getDestinationId: function _getDestinationId() {
      var config = Ember.getOwner(this).resolveRegistration('config:environment');
      if (config.environment === 'test') {
        return document.querySelector('#ember-testing > .ember-view').id;
      }
      return config['ember-basic-dropdown'] && config['ember-basic-dropdown'].destination || 'ember-basic-dropdown-wormhole';
    }
```
The problem is that `#ember-testing > .ember-view` is consistently returning null, since there's no `.ember-view` div present. Looks like it's breaking every acceptance test that navigates to a route containing an instance of the dropdown.

**Comment by stepanushariara** [comment]
@cameronblandford 

I got error like you.
can you share how to fix this error ???

**Comment by wynnfarm** [comment]
Same issue.

**Comment by luis-carlos-campos** [comment]
Same issue, Ember: 2.9.1

**Comment by mkszepp** [comment]
Closing this old issue as the mentioned code part was changed in newer versions and the initial issue was reported on a old, not anymore supported ember version
