### ISSUE TITLE
#ember-basic-dropdown-wormhole is missing on testing env

### ISSUE THREAD

**Issue by jarekpelczynski** [cibernox/ember-basic-dropdown#411]
`#ember-basic-dropdown-wormhole` is not added automatically to `content-for "body-footer"` when an app is built on the testing environment. On development and production environment the **container** exists.

**Comment by cibernox** [comment]
That is expected. In testing the target is the div where the tests run: https://github.com/cibernox/ember-basic-dropdown/blob/850c227c0a58148056d55d41aa0e5d88656b8165/addon/components/basic-dropdown.js#L273-L290
