### ISSUE TITLE
Events not registered when wormhole is outside of the DOM

### ISSUE THREAD

**Issue by alecho** [cibernox/ember-basic-dropdown#419]
I have an issue where dropdown with EPS work fine when the wormhole `div` is a child of the `body` but my custom EBD doesn't receive ember events when the wormhole div is outside of the ember app container. Moving the wormhole inside of the app container fixes this for my EBD component but breaks my EPS dropdowns in Chrome with weird positioning.

For context, I'm rendering the Ember app from within a Rails app so my Rails layout renders both the ember app container div and the wormhole div.

**Comment by alecho** [comment]
I solved this by adding a special wormhole for my component but it still seems like something is off here.

**Comment by cibernox** [comment]
This is expected. If you are using event delegation (p.e. `<button {{action "foo"}}>Submit</button>`) those actions are supposed to bubble and be handled by a global event handler in the root of the app.

However if you assign events directly with `addEventListener` or `<button onclick={{action "foo"}>Submit</button>` then events should be handed as usual.

This is not specific to EBD but to any component that is rendered outside of the ember-app.

Does this explanation make sense?
