### ISSUE TITLE
Angle Brackets Invocation requires `@class` on content component

### ISSUE THREAD

**Issue by josemarluedke** [cibernox/ember-basic-dropdown#422]
Passing just `class` to the `dropdown.content` component using the angle brackets component invocation does not work. I must call it with `@class`. Ideally it should work with just `class`.

Here is an example of not working:

```hbs
<BasicDropdown as |dropdown|>
  Trigger

  <dropdown.content class="card">  {{!-- <-------- --}}
    Some Content
  </dropdown.content>
</BasicDropdown>
```

The following does work:

```hbs
<BasicDropdown as |dropdown|>
  Trigger

  <dropdown.content @class="card"> {{!-- <-------- --}}
    Some Content
  </dropdown.content>
</BasicDropdown>
```

**Comment by cibernox** [comment]
Yes, there's a good reason for that. I'll have to rethink the component to be used as an angle-backet components, but right now you're walking unsafe grounds. There may be subtle differences in how the component works.

I should refactor the component to use the angle brackets approach but I can commit on a timeframe.

**Comment by cibernox** [comment]
@josemarluedke I believe we can close this now that we have a 2.0 beta that updates the syntax to angle-brackets
