### ISSUE TITLE
Make `handleRootMouseDown` optional

### ISSUE THREAD

**Issue by ivanvotti** [cibernox/ember-basic-dropdown#430]
First of all, thanks for creating this add-on, I really like it. In the code below I'm trying to open/close the dropdown with the computed property `areOptionsShown`. To make it work the dropdown has to be open all the time, but it closes automatically when clicking outside the dropdown. I have to use `optional` action ([ember-composable-helpers](https://github.com/DockYard/ember-composable-helpers#optional)) as a work-around:

```handlebars
{{#basic-dropdown
  class="c-dropdown"
  initiallyOpened=true
  as |dropdown|
}}
  <!-- ... -->

  {{text-input
    class="c-tags-field__input js-input"
    data-ebd-id=(concat dropdown.uniqueId "-trigger")
    <!-- ... -->
    focusIn=(toggle-action "hasInputFocus" this)
    focusOut=(toggle-action "hasInputFocus" this)
    data-test-tags-input=true
  }}

  {{#if this.areOptionsShown}}
    {{#dropdown.content class="c-dropdown__content" handleRootMouseDown=(optional)}}
      <div class="c-options c-options--small" data-test-tags-options>
        <!-- ... -->
      </div>
    {{/dropdown.content}}
  {{/if}}
{{/basic-dropdown}}
```

**Comment by cibernox** [comment]
The way I usually prevent the dropdown from closing is by passing  an `onClose` action that returns false. 

There is an example in the docs illustrating how to keep a dropdown open until the user performs one action: https://ember-basic-dropdown.com/docs/dropdown-events

**Comment by ivanvotti** [comment]
That works. Thank you.
