### ISSUE TITLE
EmberError - You must use set() to set the `previousHorizontalPosition` property

### ISSUE THREAD

**Issue by jaredgalanis** [cibernox/ember-basic-dropdown#431]
I'm getting the following error when attempting to click close on the target. Is this a known issue?

`"Assertion Failed: You must use set() to set the `previousHorizontalPosition` property (of <my-app@component:basic-dropdown::ember519>) to `null`."`

**Comment by jaredgalanis** [comment]
Closing because I'm no longer experiencing this issue. Not 100% sure what it was, but I'll comment further if I find out.

**Comment by BnitoBzh** [comment]
I have the same issue with Ember 3.10.2.
```
  <BasicDropdown as |dd|>
    <dd.trigger>{{t (concat "language." this.intl.locale.firstObject)}}</dd.trigger>
    <dd.content>
      {{#each this.languages as |language|}}
        <div {{action "setLanguage" language}}>{{t (concat "language." language)}}</div>
      {{/each}}
    </dd.content>
  </BasicDropdown>
```

**Comment by cibernox** [comment]
@BnitoBzh version of the addon?

**Comment by BnitoBzh** [comment]
@cibernox EBD@1.1.2

**Comment by BnitoBzh** [comment]
@cibernox i want to submit a pull-request for EBD@1.1.2 but there is no active branch for this version .. The master branch is on @2.x ...
On which branch can i made my pull request ?

**Comment by cibernox** [comment]
@BnitoBzh I created a 1.X branch. Try with that branch and I'll try to port the change to 2.X
