### ISSUE TITLE
'onKeyDown' option not working on ember-basic-dropdown

### ISSUE THREAD

**Issue by Willibaur** [cibernox/ember-basic-dropdown#435]
Hi all,
According to docs, `ember-basic-dropdown` V1.0.4, allows use of `onKeyDown` within `dropdown content` but it doesn't work at the moment, am I doing something wrong? :thinking: 
Thanks

```
// my-template.hbs
{{#basic-dropdown
  horizontalPosition='right'
  verticalPosition='below'
as |dropdown|
}}
  {{#dropdown.trigger}}
    <p>Account</p>
  {{/dropdown.trigger}}

  {{#dropdown.content onKeyDown=(action "keyDownAction")}}
    <p>Content</p>
  {{/dropdown.content}}
{{/basic-dropdown}}


// my-component.js
actions: {
  keyDownAction(dropdown, e) {
    if (e.keyCode === 70) {
      alert('Action triggered');
    }  
  }
}
```

**Comment by cibernox** [comment]
The code looks good, except that the dropdown doesn't contain any focusable element.
Put a text input inside the dropdown or something you can focus and type in and you should see that the action is invoked.
