### ISSUE TITLE
`renderInPlace=true || false` is not working

### ISSUE THREAD

**Issue by navin-tiwari** [cibernox/ember-basic-dropdown#439]
Hi @cibernox ,

I have been trying to use ember-basic-dropdown in my project but facing the following issue after updating the ember-power-select version: v2.2.1
I need a sticky popup on both IE11 and Chrome, popup should remain absolute.
Code :
[app.zip](https://github.com/cibernox/ember-basic-dropdown/files/2684768/app.zip).

Note : Code is working as expected for ember-power-select v1.1.0.

Can you please help me out in this scenario? 

Thanks in advance.

**Comment by navin-tiwari** [comment]
Hi @cibernox ,

Did you get a chance to look into this issue?

Thanks

**Comment by cibernox** [comment]
@navin-tiwari I did not, but I have time today. However, how do I reproduce the problem? The zip on your original comment does not contain the entire application, only the `/app` folder.

**Comment by navin-tiwari** [comment]
Hi @cibernox ,

Thanks for your time, please find below example
[demo.zip](https://github.com/cibernox/ember-basic-dropdown/files/2707574/demo.zip)

**Comment by navin-tiwari** [comment]
Hi @cibernox ,

In case you get a chance to review this issue again please reply on the same.

Thanks.

**Comment by mkszepp** [comment]
Closing this issue as it makes part of v2 and we wete landed with v8
