### ISSUE TITLE
calling set on destroyed object

### ISSUE THREAD

**Issue by knownasilya** [cibernox/ember-basic-dropdown#442]
> "calling set on destroyed object: <map@component:basic-dropdown/content::ember1608>.animationClass = ember-basic-dropdown--transitioned-in"

This seems to sneak in ever so often in my app. This is the first time I actually caught the error.

**Comment by cibernox** [comment]
If you have an idea of how it can happen submit a fix. If you can figure out a way to kill the timer that causes this that preferable to checking if the component has been destroyed
