### ISSUE TITLE
DEPRECATION: Use of `merge` has been deprecated

### ISSUE THREAD

**Issue by raphaelns-developer** [cibernox/ember-basic-dropdown#448]
```DEPRECATION: Use of `merge` has been deprecated. Please use `assign` instead. [deprecation id: ember-polyfills.deprecate-merge] See https://emberjs.com/deprecations/v3.x/#toc_ember-polyfills-deprecate-merge for more details.``` 

"ember-source": "~3.7.0",
"ember-basic-dropdown": "1.1.2"

**Comment by dbashford** [comment]
Believe that was dealt with here: https://github.com/cibernox/ember-basic-dropdown/commit/07ce116c15830b8a526c24a030a49fcd771d1b59#diff-f314d138b5f170fd0e9cbd05926608f6

**Comment by cibernox** [comment]
I also think this should be gone now, isn't it? Closing this, feel free to reopen if I'm wrong and this is not fixed.

@dbashford thanks for the link!
