### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by mikeelemuel** [cibernox/ember-basic-dropdown#450]
It would be very beneficial if you could list down the `Compatibility` of Ember version that the addon works.

**Comment by ryanlabouve** [comment]
We can kind of get this information from two spots:

Here, we can see what versions of Ember this addon runs against in CI: https://github.com/cibernox/ember-basic-dropdown/blob/master/.travis.yml#L52-L55

And here we can see what's passing/failing in these various versions:
https://travis-ci.org/cibernox/ember-basic-dropdown

**Comment by mikeelemuel** [comment]
Oh @ryanlabouve thank you for that, sorry I didn't see that. Thank you 👍
