### ISSUE TITLE
Css classes applied on the dropdown content sub-component are ignored

### ISSUE THREAD

**Issue by sumeetattree** [cibernox/ember-basic-dropdown#451]
`ember-basic-dropdown: v1.1.2`

```hbs
<BasicDropdown as |ddi|>
  <ddi.trigger class="col"><input type="text" class="form-control" readonly></ddi.trigger>
  <ddi.content class="p-2 shadow">
    <PowerCalendarRange
      @selected={{startedBetween}}
      @onSelect={{action (mut startedBetween) value="date"}}
    as |calendar| />
  </ddi.content>
</BasicDropdown>
```

Classes `p-2` and `shadow` are not applied on the `ddi.content` `div`

These are the classes that are present on the `class` attribute. I suspect it's overriding them
`ember-basic-dropdown-content   ember-basic-dropdown-content--left ember-basic-dropdown-content--below ember-basic-dropdown--transitioned-in ember-view`

**Comment by m3l1x** [comment]
+1 same here

**Comment by cibernox** [comment]
@m3l1x The branch `2.0-wip` is already usable if your app is un ember-canary and you enable the `EMBER_GLIMMER_FORWARD_MODIFIERS_WITH_SPLATTRIBUTES`. 

Until then, the answer you found is the right approach.
