### ISSUE TITLE
Angle Bracket example in readme does not work

### ISSUE THREAD

**Issue by ryanlabouve** [cibernox/ember-basic-dropdown#453]
The example of using this component provided in the readme does not work. 

(I'm happy to help either address this in docs or troubleshoot why it's not working.)

Example from the [readme](https://github.com/cibernox/ember-basic-dropdown/blob/master/README.md#usage) that doesn't work:
```hbs
<h1>Angle Bracket:</h1>
<BasicDropdown as |dd|>
  <dd.Trigger>Click me</dd.Trigger>
  <dd.Content>Content of the trigger</dd.Content>
</BasicDropdown>
```

Here is an example that works with moustache hashtag components (not sure what the proper name for these is):
```hbs
<h1>Moustache Hashtag:</h1>
{{#basic-dropdown as |dd|}}
  {{#dd.trigger}}Click me{{/dd.trigger}}
  {{#dd.content}}Content of the trigger{{/dd.content}}
{{/basic-dropdown}}
```

Here's a screenshot where you can see the Angle Bracket invocation is not working and the Moustache Hashtag is:

<img width="614" alt="burnerbdd 2019-03-08 09-41-43" src="https://user-images.githubusercontent.com/1318878/54038964-69a01500-4187-11e9-9f6b-c96a6a108010.png">

I tried to reproduce this in a twiddle, but the site had some issues loading with relevant versions of `ember-source` and `ember-basic-dropdown`. Here's a repo I made though: https://github.com/ryanlabouve/basic-dropdown-angle-bracket-demo/commit/809e62c5b0638e216b48128de797d5665e3be41f

```
DEBUG: ------------------------------- index.js:185
DEBUG: Ember      : 3.8.0 index.js:185
DEBUG: Ember Data : 3.7.0 index.js:185
DEBUG: jQuery     : 3.3.1 index.js:185
DEBUG: -------------------------------
```

**Comment by cibernox** [comment]
@ryanlabouve sorry for the inconvenience. The readme is for the master branch, which is now part of the 2.0 alpha versions. If you're installed the latest EBD 1.X it doesn't work indeed.

For now I'd recommend using curly braces syntax. I hope to finish the refactor once https://github.com/emberjs/rfcs/pull/435 is implemented. Without it element modifiers are in a weird uncanny valley that are not truly usable.

/cc @rwjblue @pzuraq

**Comment by ryanlabouve** [comment]
Ah, that makes sense.

If it's worth it I've seen other project do something like this to help folks that would assume that `README.md ` is the best source of current documentation:

```
If you're viewing this at https://github.com/collectiveidea/delayed_job, you're reading the documentation for the master branch. View documentation for the latest release (4.1.5).
```
(example via https://github.com/collectiveidea/delayed_job/blob/master/README.md)

I'll close this issue for now.

**Comment by sohara** [comment]
Personally I don't think this issue should be closed. If a user follows the instructions for the docs site they will simply have a situation where nothing renders, as described in the issue. 

@cibernox I wonder if you would consider either publishing the docs that correspond to the currently (non-alpha) released version or alternately updating the installation instructions on master to be something like `ember install ember-basic-dropdown@2.0.0-alpha.4` so that the users who follow along have a version installed that corresponds to the rest of published docs?
