### ISSUE TITLE
TypeError in addon that extends this addon.

### ISSUE THREAD

**Issue by lvegerano** [cibernox/ember-basic-dropdown#462]
I have an addon that extends this addon. It's almost a copy the only difference it that the dropdown-content component exposes a series of components for further composition. My addon has `ember-basic-dropdown` in the `dependencies` block.

In my app I require my addon, but for some reason if I don't install `ember-basic-dropdown` in my app I get `TypeError: Argument 1 of MutationObserver.observe is not an object.` It happens in the `open()` function. Seems that `this.dropdownElement` is not in the dom.

I could give access to the repo if needed.

**Comment by cibernox** [comment]
If you could share the repo it shouldn't be a problem to debug it on monday.

**Comment by lvegerano** [comment]
Just sent you an invite. Thanks a lot!

**Comment by cibernox** [comment]
@lvegerano I cloned the repo and ran the app. I can see the component but I don't see any error in the console. How can I reproduce the error?

**Comment by lvegerano** [comment]
@cibernox the dummy app works just fine. It breaks when the repo is npm installed on another app.

**Comment by cibernox** [comment]
@ivegerano gotcha, I'll check @ home

**Comment by cibernox** [comment]
@lvegerano I created a sample app and npm-linked locally `cos-basic-dropdown` and it just worked.

Is there any other think I should know?

**Comment by lvegerano** [comment]
Mmm not really. Well maybe we have something weird going on in our app. I will have to double check again. Thanks for looking into this and sorry for the inconvenience.
