### ISSUE TITLE
Classic component syntax doesn't work with Ember Dropdown 2.x version

### ISSUE THREAD

**Issue by AleksandrBorovkov** [cibernox/ember-basic-dropdown#482]
I've used Ember 3.11 with classic component syntax and Basic Dropdown component haven't appeared in DOM. When I changed classic syntax to angle brackets, it fixed this issue.

**Comment by cibernox** [comment]
That is somewhat expected, 2.0 is designed explicitly to be used in angle-bracket syntax. The docs have been completely updated to display angle-bracket syntax everywhere.
