### ISSUE TITLE
Error: Assertion Failed: '@dropdown.isOpen' is not a valid path.

### ISSUE THREAD

**Issue by cluis13915** [cibernox/ember-basic-dropdown#485]
After installed `ember-power-select`, running `ember serve` throws this error:
```
Template Compiler Error (broccoli-persistent-filter:TemplateCompiler) in ember-basic-dropdown/templates/components/basic-dropdown-content.hbs

Assertion Failed: '@dropdown.isOpen' is not a valid path. ('ember-basic-dropdown/templates/components/basic-dropdown-content.hbs' @ L2:C6)

```
Working with:
- ember-cli: 3.0.0
- node: 10.16.0
- os: linux x64

Any help is appreciated. Thanks.

**Comment by deanylev** [comment]
You need to downgrade to ember-basic-dropdown 1.13 or upgrade your Ember to 3.11 or above.

**Comment by cibernox** [comment]
@deanylev is correct, you are most likely in an older version of Ember.
