### ISSUE TITLE
triggerComponent not working as expected

### ISSUE THREAD

**Issue by drummy2** [cibernox/ember-basic-dropdown#493]
I am binding in triggerComponent with a component that extends basic-dropdown-trigger.
Previous versions the mandatory onClick seems to get added but since moving to the latest version it no longer works.  It seems, to get it to work I have use the on click in my custom triggers handlebars like so

`{{on "click" this.handleClick}}`

In the tests you don't use the on click and it renders the trigger ok but actually when clicking it doesn't bring up the menu content.

**Comment by mkszepp** [comment]
Closing this old issue, because it should work in current version and also test are up to date
