### ISSUE TITLE
Allow nesting dropdowns

### ISSUE THREAD

**Issue by cprussin** [cibernox/ember-basic-dropdown#52]
I love this addon.  One feature that appears to not work properly, however, is nesting 
dropdowns.  A simple example of where this is useful is for a submenu in a nav.  Is there a way to do this already that I'm missing?

I was thinking about taking a crack at this by instead of rendering to a single static wormhole div, creating a new div under the body tag when clicking the trigger, and pointing wormhole to that div.  That way, all drop-downs don't share the same wormhole destination.  Does this approach seem practical?

Thanks!

**Comment by cibernox** [comment]
There is one trick. Render the one inside the other with with `renderInPlace=true`. It's true that you can't have more than one dropdown rendered in the wormhole at the same time, but you can as many as you want if they are rendered in place.

**Comment by cprussin** [comment]
Oooo interesting, does this have any implications for things like z-indexing and overflows?

Will certainly try this!  Thanks!

**Comment by cibernox** [comment]
If the one outside is rendered in the body, then those inside will be inside it and be safe from z-index issues.

**Comment by cprussin** [comment]
Great, many thanks!
