### ISSUE TITLE
Issue closing dropdown using `on` modifier

### ISSUE THREAD

**Issue by barryofguilder** [cibernox/ember-basic-dropdown#528]
I have a dropdown that contains links to other pages in my Ember 3.15 app. I want the dropdown to close after the user has clicked a link.

I have this in my template:
```handlebars
<BasicDropdown as |Dropdown|>
  <Dropdown.Trigger>
    Click Me
  </Dropdown.Trigger>
  <Dropdown.Content>
    <div>
      <div {{on "click" (fn this.menuItemClicked Dropdown)}}>
        <LinkTo @route="route-one">
          Route 1
        </LinkTo>
        <LinkTo @route="route-two">
          Route 2
        </LinkTo>
      </div>
    </div>
  </Dropdown.Content>
</BasicDropdown>
```

And in my `controller.js` file:
```javascript
@action menuItemClicked(dropdown) {
  dropdown.actions.close();
}
```

The problem is that when I click a link, the dropdown properly closes, but then it does a hard refresh when going to the link in my app. This means that any state I had in my app is completely gone. I created a [very simple repository](https://github.com/barryofguilder/ember-basic-dropdown-issue) to reproduce the issue and I still get the same behavior.

This issue _doesn't_ happen if I comment out the `dropdown.actions.close()` in my action. I can  also get this working if I use the `action` modifier instead of the `on` modifier in the template like so:
```handlebars
...
<div {{action this.menuItemClicked Dropdown}}>
...
```

I'm not really sure what's going on. Is this an issue with `ember-basic-dropdown`? Is this an issue with the `on` modifier or `fn` helper? I really don't know where to start.

**Comment by barryofguilder** [comment]
Just to add a little more insight to this, if I use a `button` instead of a `LinkTo` and add a `click` event to transition to the same route, it works fine. It seems to only be an issue when I'm using `LinkTo` or `{{link-to}}`.

**Comment by cibernox** [comment]
that's weird. I can only guess that there's something weird with link-to in which if the link is removed from the page before the event is actually handled something doesn't work as expected. But I don't think it's specific to Ember Basic Dropdown, my guess is that it would happen with any link that disappears from the page too quickly.

**Comment by cibernox** [comment]
Closing as I suspect it's not a problem with ember-basic-dropdown itself, as using a button proves to work.

**Comment by wozny1989** [comment]
@barryofguilder I was able to solve this problem. I'm not sure this is a perfect solution, but it works:
```js
import Component from '@glimmer/component';
import { action } from '@ember/object';
import { next } from '@ember/runloop';

export default class ExampleComponent extends Component {
  @action
  onClick() {
    next(this, () => {
      this.args.dropdown.actions.close();
    });
  }
}

```

**Comment by Techn1x** [comment]
Same issue here, workaround works great.

It is very strange though, any click handler on my LinkTo's work just fine (say, for analytics). But once one of those click handlers calls the dropdown close action, the router decides to hard refresh.

Stepping through the close aciton, it all works fine, no crashes etc. But somehow the LinkTo / ember router is aware that this dropdown close action is being called, not liking it, and refreshing...

Definitely something really weird going on!

**Comment by Techn1x** [comment]
Just a guess:
The dropdown closes just before LinkTo finishes. LinkTo destroyed. router wonders where its element went & doesn't like that.
That's why next works

**Comment by mkszepp** [comment]
this bug is nothing which we can handel in ebd...

The browser handels the event one by one... the event listener order depends on browser side and there no guarantee in which order he works them...
The only safe way is, creating a button with `{{on "click" this.onClick}}` and handel inside this action closing and redirect.

When you are using a next you need also always to check if `this.args.dropdown` api is still present (and maybe also if component is not destory...) otherwise you run possible on other error cases

**Comment by Techn1x** [comment]
> When you are using a next you need also always to check if this.args.dropdown api is still present (and maybe also if component is not destory...) otherwise you run possible on other error cases

Thanks! will make sure to do so

**Comment by Techn1x** [comment]
> The browser handels the event one by one... the event listener order depends on browser side and there no guarantee in which order he works them...

yeah you're right. The click handler for the LinkTo wouldn't get called yet, so wouldn't preventDefault, and would end up continuing with the default click href logic that reloads the page. Makes sense.
