### ISSUE TITLE
Compiled types missing from npm package

### ISSUE THREAD

**Issue by billdami** [cibernox/ember-basic-dropdown#542]
When attempting to import modules from the addon (v3.0.1) in a TypeScript ember application, e.g.
```ts
import BasicDropdownTrigger from 'ember-basic-dropdown/components/basic-dropdown-trigger';
```
Errors like `Cannot find module 'ember-basic-dropdown/components/basic-dropdown-trigger'.` are returned. 

It looks like this is because the downloaded npm package does not include the compiled type files that it expects in those locations, i.e. `node_modules/ember-basic-dropdown/components/basic-dropdown-trigger.d.ts` which ember-cli-typescript should normally be generating as part of the `prepublishOnly` step when publishing the package.

**Comment by netes** [comment]
Bumping.

**Comment by mkszepp** [comment]
TS types are now complete in v8
