### ISSUE TITLE
Alter trigger tag name? (^3.0.0) 

### ISSUE THREAD

**Issue by Kilowhisky** [cibernox/ember-basic-dropdown#543]
I'm working on upgrading from 2x to 3x and i've run into a problem where my CSS requires that the element be `button` but the trigger forces it to be a `div`.  Is there a reason the tag name can't be overridden to be anything other than `div`? Wouldn't `button` be more syntactically correct?

https://github.com/cibernox/ember-basic-dropdown/blob/ea50fb854475d0e8d865ab8174c5c4138d152e25/addon/templates/components/basic-dropdown-trigger.hbs#L1

Couldn't a simple. `this.args.tagName` work? That would allow for backwards compatibility. 

What are your thoughts?

**Comment by Kilowhisky** [comment]
Actually, i see that you pulled that block straight from the RFC for dynamic tags. 

https://emberjs.github.io/rfcs/0389-dynamic-tag-names.html#how-we-teach-this
```
{{!-- sidebar.hbs, a template-only component --}}
{{#let (element (or @htmlTag "aside")) as |Tag|}}
  <Tag ...>...</Tag>
{{/let}}
```
```
<Sidebar @htmlTag="nav">...</Sidebar>
```
So i gave it a shot putting in the `@htmlTag` and it worked!
```
<dd.Trigger @htmlTag="button" class='button' title={{t 'track.trackFilterTitle'}}>
    <i class="ico-filter {{if filtersSet 'active'}}"></i>
</dd.Trigger>
```

Any way this can be listed as public API?

**Comment by mkszepp** [comment]
Its a old issue, but only as info
`@htmlTag` is already documented and tag can be oberwrittwn
