### ISSUE TITLE
`throwUnlessParallelizable` and was unable to parallelize a plugin

### ISSUE THREAD

**Issue by jmonster** [cibernox/ember-basic-dropdown#547]
I think this is a silent but common problem across the ember ecosystem, but this particular repo is the one one currently blocking my project from building in parallel:

```sh
THROW_UNLESS_PARALLELIZABLE=1 yarn start
$ ember serve
[broccoli-persistent-filter:Babel > [Babel: ember-basic-dropdown]: Babel: ember-basic-dropdown] was configured to `throwUnlessParallelizable` and was unable to parallelize a plugin.
plugins:
1: name: unknown, location: unknown
```

**Comment by veelci** [comment]
I'm running into the same problem using both v2.0.15 and v3.0.21 of ember-basic-dropdown in separate projects.

**Comment by cibernox** [comment]
I'm not very familiar with what makes an addon parallelizable. What can be done on this addon to make it parallel?

**Comment by teakap** [comment]
@cibernox I'm experiencing the same issue. I think this is what you want to make it parallelizable: 

https://github.com/babel/broccoli-babel-transpiler#parallel-transpilation

**Comment by teakap** [comment]
A bit more info about the warnings, on a fresh ember app.  

After `ember-power-select`  installation. 
<img width="1325" alt="testing_ember_power_select" src="https://user-images.githubusercontent.com/13741777/180053298-d8e152bc-7dbf-4f39-9c1f-19ab6d9b6846.png">


After `ember-basic-dropdown` installation. 
<img width="1451" alt="testing_ember_basic_dropdown" src="https://user-images.githubusercontent.com/13741777/180053484-2b1b3bb1-749a-49f8-86b0-e7b2a7251c1a.png">

**Comment by sly7-7** [comment]
@teakap I don't know if it's related, but I just encountered this error after upgrading ember-data to 4.6. I realized that an other addon was using ember-data on 3.28. having the two pointing to 4.6, nuking node_modules, and yarn.lock file, makes the build to work again.

@cibernox I also found https://github.com/typed-ember/ember-cli-typescript/pull/351/files where it seems to workaround the problem (but to be honest, I don't understand what that mean).

**Comment by mwhitworth** [comment]
From a brief investigation (`console.log` calls in `broccoli-babel-transpiler`), I think the `ember-maybe-in-element` dependency is the culprit - see https://github.com/DockYard/ember-maybe-in-element/issues/52 and the open PR https://github.com/DockYard/ember-maybe-in-element/pull/54 to address this issue

**Comment by mwhitworth** [comment]
I think this can be closed, since the issue lies in another project (which has already addressed the issue)
