### ISSUE TITLE
Animating dropdown

### ISSUE THREAD

**Issue by cprussin** [cibernox/ember-basic-dropdown#57]
Hi!

I'm not sure if this should be an issue or possibly a wiki article, or maybe in the readme.  But, do you have any suggestions for animating the dropdown?  I've tried a few approaches using css transitions and using liquid-fire, and I find it difficult to do well because it appears that everything I've tried is messing up the positioning on the drop until the drop is fully open.  So for instance, it will animate, but the drop will open far to the right of where it should be on the page, and then jump to the correct location after the animation is done.

Thanks!

**Comment by cibernox** [comment]
If you animate the position of the dropdown using `transform: translate` you still get positioning problems?

**Comment by cibernox** [comment]
Closed since the addon has animations in a stable version.
