### ISSUE TITLE
Upgraded packages

### ISSUE THREAD

**Issue by utf4** [cibernox/ember-basic-dropdown#578]
I upgraded some of the packages in a project i was working on, now i am seeing this error when starting server

```
Template Compiler Error (broccoli-persistent-filter:TemplateCompiler) in ember-basic-dropdown/templates/components/basic-dropdown-content.hbs

Compile Error: ...attributes can only be used in an element
```

**Comment by cibernox** [comment]
Could you give more information? Ember version, version of ember-basic-dropdown, etc..

**Comment by furqanaziz** [comment]
ember-cli => 3.2.0
ember-source => 3.2.2
ember-basic-dropdown => 2.0.15

**Comment by pkimmlinger** [comment]
Hi, got the same issue after upgrading ember-cli package from 3.2.0 to 3.22.0.

**Comment by tlockhart** [comment]
Any update on this?  I'm getting the following error after ember 3.25.2 `upgrade:
`errorMessage: ember-basic-dropdown/templates/components/basic-dropdown-content.hbs: Cannot read property 'type' of undefined
        in /tmp/broccoli-2011rMhW5Q23vF5N/out-0859-colocated_template_processor`

**Comment by cibernox** [comment]
I didn't know this was still an issue. I'll look into it.

**Comment by bjornharrtell** [comment]
I also got the one mentioned above:

Template Compiler Error (broccoli-persistent-filter:TemplateCompiler) in ember-basic-dropdown/templates/components/basic-dropdown-content.hbs

Cannot read property 'type' of undefined

This can reproduced by upgrading to ember-source to 3.25.0 on the v2 branch. 3.24.3 appears to work.

**Comment by Kilowhisky** [comment]
![image](https://user-images.githubusercontent.com/7075666/113444407-b2e3e280-93a8-11eb-946a-16f5cbcb79ab.png)

Upgrading to ember `> 3.25` does this to me. If i drop below that everything still works.

**Comment by leils** [comment]
Also getting this issue, using ember-source 3.1.4 and dropdown 2.0.15
Goes as far back as ember-paper beta.27

**Comment by mohitsud** [comment]
anyone find a fix for it?

**Comment by mkszepp** [comment]
Closing issue, cause it was maybe already fixed with newer addon version.
If occures with current version, feel free to reopen this issue
