### ISSUE TITLE
Cannot import ember-basic-dropdown

### ISSUE THREAD

**Issue by sidharthanil** [cibernox/ember-basic-dropdown#580]
Sass Syntax Error (SassCompiler) in C:\Users\anils\AppData\Local\Temp\broccoli-110360ExHm89CSBCD\out-307-broccoli_merge_trees_full_application\\app\styles\app.scss:2:9

Error: Can't find stylesheet to import.
  ╷
2 │ @import "ember-basic-dropdown";
  │         ^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  C:\Users\anils\AppData\Local\Temp\broccoli-110360ExHm89CSBCD\out-307-broccoli_merge_trees_full_application\app\styles\app.scss 2:9  root stylesheet

**Comment by mkszepp** [comment]
I know, its a old issue and maybe also already resolved.
I will close it, but feel free to reopen, if this bug occures with latest version
