### ISSUE TITLE
Question: dropdown content box sizing - necessary?

### ISSUE THREAD

**Issue by Techn1x** [cibernox/ember-basic-dropdown#585]
Due to the `*` css selector below, this affects some of the components we intend to place in a dropdown. We can override it no problem, but is it necessary in the first place? Does anyone know why?

https://github.com/cibernox/ember-basic-dropdown/blob/946b4ef51714eba56a5c94fa9db4e7cf3103c9b8/vendor/ember-basic-dropdown.css#L4-L5

Thanks!

**Comment by cibernox** [comment]
To be honest, I don't remember why I put it, it was years ago. 
At this point I can only assume that if it's there it's probably it was necessary at some point.

I'm a bit wary of removing it right now, so if you can add
` .ember-basic-dropdown, .ember-basic-dropdown-content, .ember-basic-dropdown-content * { 
   box-sizing: content-box; } ` please do.
