### ISSUE TITLE
issue with embroider

### ISSUE THREAD

**Issue by alexborovkov** [cibernox/ember-basic-dropdown#600]
ember-basic-dropdown@3.0.13
    "@embroider/compat": "^0.36.0",
    "@embroider/core": "^0.36.0",
    "@embroider/macros": "^0.36.0",
    "@embroider/router": "^0.36.0",
    "@embroider/util": "^0.36.0",
    "@embroider/webpack": "0.36.0"

Module Error (from /Users/aborovkov/Documents/work/web/node_modules/@embroider/hbs-loader/src/index.js):
Unsafe dynamic component: cannot statically analyze this expression in node_modules/ember-basic-dropdown/templates/components/basic-dropdown-content.hbs

![image](https://user-images.githubusercontent.com/22237897/108762435-218b8000-7561-11eb-84ca-dd2aaf1624a5.png)

**Comment by gilest** [comment]
Just noticed this myself. Will affect cibernox/ember-power-select/pull/1419 also

**Comment by gilest** [comment]
Investigated this today and believe it may be fixed by tildeio/ember-element-helper/pull/34

**Comment by lukemelia** [comment]
That ember-element-helper PR has been released as 0.5.0.

**Comment by cibernox** [comment]
Updated ember-basic-dropdown and ember-power-select to use ember-element-helper ^0.5.0.

Hopefully that fixes all embroider problems
