### ISSUE TITLE
Does not work inside Shadow DOM

### ISSUE THREAD

**Issue by lolmaus** [cibernox/ember-basic-dropdown#617]
Hi!

We use Shadow DOM to allow embedding our app into any website. It solves the following problems of `<iframe>`:

* Modal backdrop and sidebar modals are rendered to the whole viewport and not contained in a smaller rectangle.
* Host website styles do not leak into the app, do not deface it and do not require ugly overrides.

Shadow DOM, in the absence of alternative solutions, is crucial to our business.

Ember works flawlessly in Shadow DOM, it does not require any modifications (beyond embedding itself, for which we have a solution: https://github.com/kaliber5/ember-embedded-snippet/ ). But Shadow DOM breaks all addons that rely on things like `document.getElementById` which fails to look up elements inside Shadow DOM.

`ember-basic-dropdown` and, by extension, `ember-power-select` are the biggest offenders.

CC @simonihmig

**Comment by BlueCutOfficial** [comment]
Hi!
I join the `#needShadowDOM` team ^^ 
We also want to use Shadow DOM to serve our app as a Web Component, so we face the same issue as we rely on `ember-basic-dropdown` for all our datepickers, calendar or other selects.

**Comment by mkszepp** [comment]
closed with #791
