### ISSUE TITLE
fails to build in ember 3.27.0

### ISSUE THREAD

**Issue by BryanCrotaz** [cibernox/ember-basic-dropdown#624]
```
Template Compiler Error (broccoli-persistent-filter:TemplateCompiler) in ember-basic-dropdown/templates/components/basic-dropdown/content.hbs

Assertion Failed: [BUG] seen set should be available
```

Builds ok in 3.20.0 (used ember-cli-update to do the upgrade)

**Comment by gabivoicu** [comment]
Seeing the same error, except is fails in `3.20.0` as well.

**Comment by juanazam** [comment]
@BryanCrotaz if you are seeing this while installing `ember-paper`, this happens because ember paper uses an old version of the addon https://github.com/miguelcobain/ember-paper/blob/master/package.json#L68 (2.0.15)

The latest version of this addon is 3.0.19

**Comment by icheered** [comment]
@juanazam Do you know if there is a way to manually set the `ember-paper` dependency to that specific version?

**Comment by juanazam** [comment]
@icheered you can pin the version using `resolutions` if you use yarn, but the version ember paper uses is too old to do that

**Comment by burritoIand** [comment]
also getting failure after updating to `3.27.0`, any suggestions?
```
TypeError: Cannot read properties of undefined (reading 'args')
                at initializer (https://0.0.0.0:7357/assets/vendor.js:99689:19)
                at getter (webpack://__ember_auto_import__/./node_modules/@glimmer/validator/dist/modules/es2017/lib/tracking.js?:88:15)
                at BasicDropdown.get [as isOpen] (webpack://__ember_auto_import__/./node_modules/@glimmer/tracking/dist/modules/es2017/src/tracked.js?:107:14)
                at BasicDropdown.get publicAPI [as publicAPI] (https://0.0.0.0:7357/assets/vendor.js:99405:22)
                at getPossibleMandatoryProxyValue (https://0.0.0.0:7357/assets/vendor.js:13809:19)
                at _getProp (https://0.0.0.0:7357/assets/vendor.js:13874:17)
                at https://0.0.0.0:7357/assets/vendor.js:49294:45
                at https://0.0.0.0:7357/assets/vendor.js:49242:37
                at track (https://0.0.0.0:7357/assets/vendor.js:58931:7)
                at valueForRef (https://0.0.0.0:7357/assets/vendor.js:49241:44)
```

**Comment by juanazam** [comment]
@burritoIand seems you are using an old version of the addon, the newer ones work with 3.27

**Comment by burritoIand** [comment]
@juanazam 
![image](https://user-images.githubusercontent.com/230757/132266639-4110c02a-8d2c-4100-8a60-eb93bc4336f5.png)
I didn't investigate further but I'll try again tonight or tomorrow.. all I know is my test suite had multiple failures with same message above after bumping to ember 3.27

**Comment by BryanCrotaz** [comment]
Check with ember-dependency-lint that you don't have multiple versions loaded

**Comment by burritoIand** [comment]
@BryanCrotaz ok will check, loaded the app and saw this:
![image](https://user-images.githubusercontent.com/230757/132310357-46f751c2-8e5c-4995-a8e1-de19336cd991.png)

**Comment by timmorey** [comment]
@burritoIand I also ran into the `Cannot read property 'args' of undefined` error when I updated to ember 3.27.  I found that I had conflicting resolutions for `@glimmer/tracking` in my lockfile, causing both 1.0.1 and 1.0.4 to be available.  I massaged the lockfile to get all references to resolve to 1.0.4, and the error went away.

**Comment by kategengler** [comment]
Seen this upgrading ember-source from 3.24.8 to 3.28.5 using 4.0.3 of this addon.

**Comment by twcus** [comment]
Anyone find a solution for this? I'm seeing the exact same error after upgrading to Ember 3.28.

 "ember-source": "~3.28.8",
"ember-cli": "~3.28.5",
"ember-basic-dropdown": "^6.0.0"

`Template Compiler Error (broccoli-persistent-filter:TemplateCompiler) in ember-basic-dropdown/templates/components/basic-dropdown-content.hbs

Assertion Failed: [BUG] seen set should be available`

Was previously building on ember-source 3.21.1 and ember-basic-dropdown 4.x  just fine.

**Comment by mkszepp** [comment]
Closing this issue, as this bug was reported with v3 / v4 and maybe also already fixed with dependencies

If it is still present with v8 (and ember v3.28+) let me know
