### ISSUE TITLE
Resolve multiple versions of @embroider/util

### ISSUE THREAD

**Issue by mayatron** [cibernox/ember-basic-dropdown#636]
Running `ember dependency-lint` fails with:

```
@embroider/util
Allowed: (any single version)
Found: 0.47.2, 0.41.0
my-app
└─┬ ember-basic-dropdown
  ├── @embroider/util@0.47.2
  └─┬ ember-element-helper
    └── @embroider/util@0.41.0
```

**Comment by tschoartschi** [comment]
I stumbled across the same problem. I think it's also reported here: https://github.com/cibernox/ember-power-select/issues/1499

@mayatron did you find a way to work around the problems with `ember dependency-lint` until they fix this issue?

**Comment by mkszepp** [comment]
should be fixed with: https://github.com/cibernox/ember-basic-dropdown/pull/654
