### ISSUE TITLE
Persistent Deprecation Warning With Ember 3.28

### ISSUE THREAD

**Issue by sdellisImpinj** [cibernox/ember-basic-dropdown#640]
After upgrading to Ember 3.28, I start to see this whenever I build the app:

`DEPRECATION: registerPlugin is deprecated, please pass plugins directly via `compile` and/or `precompile`. [deprecation id: template-compiler.registerPlugin]`

This appears to be due to ember-maybe-in-element not updating their version of ember-cli-htmlbars:
https://github.com/DockYard/ember-maybe-in-element/issues/47

Unfortunately, that repo hasn't been touched since May of 2021 and the filed issue hasn't received any attention. Thus, I'm wondering whether it's worth using that repo at all, particularly when it's only providing a small convenience function.

**Comment by raido** [comment]
For me deduplication of packages solved it - https://github.com/DockYard/ember-maybe-in-element/issues/47#issuecomment-1039088546

**Comment by sdellisImpinj** [comment]
Updating to the latest version of ember-basic-dropdown and running radio's deduplication suggestion resolved this for me.
