### ISSUE TITLE
Type error for getOwner 

### ISSUE THREAD

**Issue by josemarluedke** [cibernox/ember-basic-dropdown#645]
When using v4 of `@types/ember__application`, we get error because getOwner now returns unknown.

```
../../node_modules/ember-basic-dropdown/addon/components/basic-dropdown.ts:318:18 - error TS2571: Object is of type 'unknown'.

318     let config = getOwner(this).resolveRegistration('config:environment');
                     ~~~~~~~~~~~~~~
Found 1 error.
```

I suggest moving to `ember-get-config`.

**Comment by cibernox** [comment]
Good point. I'm a bit short of time lately tho, do you reckon you can make a PR using `ember-get-config`?

**Comment by bertdeblock** [comment]
I have very little TS experience, so forgive my ignorance, but isn't there another TS specific way this can be resolved that doesn't affect non TS users? I don't think using `ember-get-config` is a great alternative to the lookup we had before, my app's config is now included 3 times in the final build (see https://github.com/mansona/ember-get-config/issues/39) and `ember-get-config` v1 also gets the config at runtime from a different location.

**Comment by bertdeblock** [comment]
It seems this can be solved in TS land without switching to `ember-get-config`:
https://discord.com/channels/480462759797063690/484421406659182603/964057832838291486
