### ISSUE TITLE
Documentation website is down

### ISSUE THREAD

**Issue by matthew-robertson** [cibernox/ember-basic-dropdown#649]
More of a heads up than anything. It looks like [https://ember-basic-dropdown.com/](https://ember-basic-dropdown.com/) has been inaccessible for at least the last day or so. I double checked on a few devices+networks to be sure the problem wasn't on my end.

This doesn't apply to ember-power-select's documentation.

**Comment by hoIIer** [comment]
seeing it as well here

**Comment by hoIIer** [comment]
@cibernox

**Comment by cibernox** [comment]
Aaaaand it's back up! Thanks for letting me know!

**Comment by matthew-robertson** [comment]
Can confirm it's back up, thanks for getting to it so quickly!

**Comment by flashios09** [comment]
@cibernox The website https://ember-basic-dropdown.com is down again

**Comment by flashios09** [comment]
The website is back, thanks @cibernox !

**Comment by cibernox** [comment]
@flashios09 I should pay more attention to any email with "Domain expiration" in the subject 😝
