### ISSUE TITLE
Works in version 5, not in version 6.

### ISSUE THREAD

**Issue by BnitoBzh** [cibernox/ember-basic-dropdown#667]

**Comment by cibernox** [comment]
Can I get some more info?

**Comment by BnitoBzh** [comment]
yes, i would like, but i have no extra data .. there no error in the console.
i have tested with this simple example : 
```
<BasicDropdown as |dd|>
  <dd.Trigger>Click me</dd.Trigger>
  <dd.Content>Hello world</dd.Content>
</BasicDropdown>
```
Works perfectly with the version 5, but not with the version 6.
When I clicked on the trigger, the body classes are added, when I release the trigger, there is no content displayed.

**Comment by cibernox** [comment]
v6 was released a few hours ago and requires Ember 3.24+. Maybe that can be the reason?

**Comment by BnitoBzh** [comment]
I'm using Ember 3.28

**Comment by cibernox** [comment]
Well, something else must be going on your app because I know for a fact that the dropdown works. Can you check in your package-lock.json what version is being installed. In case there are conflicting versions.

**Comment by BnitoBzh** [comment]
The error comes from `ember-modifier`. A conflict when an app use `ember-modifier` in version 2 and 3.
After upgrading some dependencies in order the get only the lastest version of `ember-modifier` it works.
