### ISSUE TITLE
Can someone open a tracking branch for v4

### ISSUE THREAD

**Issue by mansona** [cibernox/ember-basic-dropdown#671]
I would love to backport https://github.com/cibernox/ember-basic-dropdown/pull/669 to version 4 of this repo but I can't open a PR to a branch that doesn't exist yet 😂 

Essentially v4 of ember-basic-dropdown is the latest version that currently works with ember-power-select and I want to fix that downstream dependency. The alternative is to update ember-power-select to a later version of ember-basic-dropdown but unfortunately that doesn't look like it's going to be so straight-forward 🙈 https://github.com/cibernox/ember-power-select/pull/1524

**Comment by mansona** [comment]
I ended up backporting the fix for ember-get-config because it was causing such a problem with the wider community.

Having said that, if we open a v4 branch we could update ember-style-modifier and fix this issue https://github.com/cibernox/ember-power-select/issues/1523

**Comment by mkszepp** [comment]
Closing issue, cause we have alrady v7 and are releasing v8 in next time
