### ISSUE TITLE
_actions deprecation in 2.1.0

### ISSUE THREAD

**Issue by willrax** [cibernox/ember-basic-dropdown#7]
as discussed in slack, using ember 2.1.0 i get the following deprecation warning. 

![screen shot 2015-11-02 at 11 30 49](https://cloud.githubusercontent.com/assets/94960/10880717/747c9ebc-8155-11e5-8ad6-e34f552d60a8.png)

**Comment by corrspt** [comment]
Also happens in Ember 2.0!

**Comment by cibernox** [comment]
It's next on my list

**Comment by cibernox** [comment]
Closed via #8 and released in 0.4.2

**Comment by cibernox** [comment]
Next version of ember-power-select will include this

**Comment by willrax** [comment]
Awesome. Thank you. :)
