### ISSUE TITLE
ember-basic-dropdown import @ember/test-helpers not resolvable

### ISSUE THREAD

**Issue by greg-fischer** [cibernox/ember-basic-dropdown#702]
Just started getting this while trying to run "ember s" today.
Shows this error in the build log.
```
ember-basic-dropdown tried to import "@ember/test-helpers" in "ember-basic-dropdown/test-support/helpers.js" but the package was not resolvable
```
Looks like something changed in my yarn.lock.
I have a changed reference to ember-power-select-6.0.2 which shows a dependency to:
```
    ember-basic-dropdown "^7.0.1"
```
Ember s totally fails.  I've tried cleaning all my yarn caches and rebuilding, and reverting to old code revs, we are always forced to v7 on ember-basic-dropdown suddenly.  
We're running ember 3.28 currently.

**Comment by greg-fischer** [comment]
Sorry! Just realized after writing this what this error is actually saying:  I don't have @ember/test-helpers in my package.json.   Added and I'm good. 
You can close this. :)

**Comment by navels** [comment]
We are running into this problem with `ember-basic-dropdown` in our Ember v3.28 application.  Production build is fine (this is from vendor.js, reformatted for clarity):
```
;define("ember-basic-dropdown/components/basic-dropdown", [
  "exports",
  "@ember/component",
  "@glimmer/component",
  "@glimmer/tracking",
  "@ember/object",
  "@ember/object/internals",
  "ember-basic-dropdown/utils/calculate-position",
  "@ember/runloop",
  "ember-get-config",
  "@ember/template-factory"
], function (_exports, _component, _component2, _tracking, _object, _internals, _calculatePosition, _runloop, _emberGetConfig, _templateFactory) {
```
but in our development build:
```
;define("ember-basic-dropdown/components/basic-dropdown", [
  "exports",
  "@ember/component",
  "@glimmer/component",
  "@glimmer/tracking",
  "@ember/object",
  "@ember/object/internals",
  "ember-basic-dropdown/utils/calculate-position",
  "@ember/runloop",
  "ember-get-config",
  "@ember/template-factory",
  "@embroider/macros/runtime",
  "@embroider/macros/es-compat2",
  "@ember/test-helpers"
], function (_exports, _component, _component2, _tracking, _object, _internals, _calculatePosition, _runloop, _emberGetConfig, _templateFactory, _runtime, _esCompat, _importSync20) {
```
there is a dependency on `@ember/test-helpers` that fails to resolve even though we have `@ember/test-helpers` in `devDependencies`.

@cibernox @greg-fischer  Any help on how to get `@ember/test-helpers` to make it into our development build would be highly appreciated.

**Comment by mkszepp** [comment]
@navels which `@ember/test-helpers` version are you using and which version of `ember-basic-dropdown`? Is it possible that you have `ember-basic-dropdown` v7 installed or maybe an other dependency brings v7?

**Comment by navels** [comment]
@ember/test-helpers: 2.9.6
ember-basic-dropdown: 7.3.0 via ember-power-select 7.2.0

**Comment by mkszepp** [comment]
@navels can you try to update ember-basic-dropdown to v8 & power select also to v8 (both packages are supporting ember v3.28+)

It should be simple you can follow this steps:
- https://ember-power-select.com/docs/migrate-7-0-to-8-0
- https://ember-basic-dropdown.com/docs/migrate-7-0-to-8-0 

are you using classic build or embroider?

**Comment by navels** [comment]
I seem to have gotten my app into a good state by going back through the `pnpm update` and `pnpm audit --fix` process in baby steps (one dependency at a time).  The only interesting difference is that in the working state the `@embroider/macros` version is `1.15.1` and in the non-working state it is `1.17.2`.

So unblocked for now but will try switching to embroider/vite build from classic next since it seems like a good thing to do.  Will deal with upgrading to dropdown v8 after that.  Thanks for the pointers.

**Comment by ollar** [comment]
any chances to fix this on v6? we are not ready to switch to v8 yet.
