### ISSUE TITLE
Issues under ember-cli 5

### ISSUE THREAD

**Issue by Techn1x** [cibernox/ember-basic-dropdown#706]
ember-cli 5 was released recently. ember-basic-dropdown causes an error on build
`can't read availablePlugins of undefined` (paraphrased the error because I don't have it handy)

For the time being I've implemented a patch in my own repo so that it works - I don't run sass or less so this is fine for me, but won't be for others. It looks like something in the update means that `app.registry` is undefined

```diff
diff --git a/index.js b/index.js
index 4a507e525f720ae89f4d63a737094c05006f30f7..26b28358019c7886608b4c51bf06e30681e9239a 100644
--- a/index.js
+++ b/index.js
@@ -12,14 +12,8 @@ module.exports = {
     app.__emberBasicDropdownIncludedInvoked = true;
     this._super.included.apply(this, arguments);

-    let hasSass = !!app.registry.availablePlugins['ember-cli-sass'];
-    let hasLess = !!app.registry.availablePlugins['ember-cli-less'];
-
-    // Don't include the precompiled css file if the user uses a supported CSS preprocessor
-    if (!hasSass && !hasLess) {
-      if (!app.__skipEmberBasicDropdownStyles) {
-        app.import('vendor/ember-basic-dropdown.css');
-      }
+    if (!app.__skipEmberBasicDropdownStyles) {
+      app.import('vendor/ember-basic-dropdown.css');
     }
   },
```

**Comment by rykov** [comment]
This is also an error in [cibernox/ember-power-select](https://github.com/cibernox/ember-power-select):
https://github.com/cibernox/ember-power-select/blob/812b32f0ff60ec97243de2756f7de8d1554aa034/index.js#L26-L27

**Comment by fastindian84** [comment]
It is better to use:

```js
    let hasSass = !!app.project.addonPackages['ember-cli-sass'];
    let hasLess = !!app.project.addonPackages['ember-cli-less'];
```

I believe `app.registry.availablePlugins` was replaced with `app.project.addonPackages`

**Comment by rykov** [comment]
@fastindian84 Is there a way to shim `app.registry.availablePlugins` in one's app before addons are loaded as a quick-fix until `ember-basic-dropdown` is fixed?

**Comment by fastindian84** [comment]
The easiest way is to clone a repo and fix it by hand

**Comment by rykov** [comment]
Note, I've also had success with putting the following in `package.json`:

```json
  "resolutions": {
    "ember-cli-preprocess-registry": "^3.0.1"
  }
```
