### ISSUE TITLE
Error: Assertion Failed: The `element` helper polyfill encountered an unexpected error.

### ISSUE THREAD

**Issue by evoactivity** [cibernox/ember-basic-dropdown#713]
```
ember-source:       5.3.0
@embroider/compat:  3.2.1
@embroider/core:    3.2.1
@embroider/router:  2.1.3
@embroider/webpack: 3.1.5
```

Works if I patch the components to use `-element` instead of `element`.

eg

```hbs
{{#let (-element (or @htmlTag "div")) as |OptionalTag|}}
```

**Comment by NullVoxPopuli** [comment]
what  package manager are you using / do you have a repro repo?

**Comment by evoactivity** [comment]
Using pnpm

output of `pnpm why ember-element-helper`
```
devDependencies:
ember-animated 1.0.4
└── ember-element-helper 0.6.0
ember-basic-dropdown 7.2.2
└── ember-element-helper 0.8.4
ember-power-select 7.1.2
└─┬ ember-basic-dropdown 7.2.2
  └── ember-element-helper 0.8.4
```

I don't have a repro repo at the moment, not sure when I'll be able to create one, but I'll update once I have one.

**Comment by NullVoxPopuli** [comment]
Does pnpm dedupe cause any change in your project?

**Comment by evoactivity** [comment]
No difference, still need to run my patch.

**Comment by mkszepp** [comment]
I think, that is not directly our addon which generats this bug.
Let me know if this bug is still present with v8 of ebs
