### ISSUE TITLE
destination and position of dropdown

### ISSUE THREAD

**Issue by lmcardle** [cibernox/ember-basic-dropdown#72]
I am seeing two issues in my app with this component. 

For the first issue, unless I specify the destination, destination="foo", the dropdown always appears at the very top of the page.

With the second issue, the position is not being picked up. What I mean by that is, when the target is all the way at the bottom of the page, the dropdown should reposition and display the dropdown above the target...but it does not. Similarly, if I add "verticalPosition=above" it has no affect and the dropdown is always below the target.

My feeling is that these two issues are related. Sadly, I can not reproduce the issues in a brand new clean app that only contains this plugin...so I must have something that is interfering. Any thoughts on what might be causing these two issues?

**Comment by cibernox** [comment]
Maybe it's related with the wormhole destination div not being added to the root of the body properly. There is an entry in the troubleshooting page of ember-power-select (which uses ember-basic-dropdown underneath) about this topic ([Nothing is rendered when I click the select](http://www.ember-power-select.com/docs/troubleshooting))

Maybe the root your app is the `<body>` element or you have a customized  index.html that is preventing the whormhole div from being inserted?

**Comment by lmcardle** [comment]
The issue was clashing CSS properties. :( Thanks though.
