### ISSUE TITLE
question - styles in version 8

### ISSUE THREAD

**Issue by Techn1x** [cibernox/ember-basic-dropdown#788]
I've updated from 7.3.0 to 8.0.0-beta.7 today

One thing I overcame was, previously the positioning styles were just applied for me (likely due to the v1 addon setup), whereas now I've had to import them (I added this line to my `app.ts` file)
```ts
import "ember-basic-dropdown/vendor/ember-basic-dropdown.css";
```

Just wondering if that's the intended way for downstream applications to consume the styles now, or was it intended to remain automatic, since it wasn't mentioned in the breaking changes?

**Comment by Techn1x** [comment]
> I've had to import them (I added this line to my app.ts file)

Though, this actually ends up with a different result for me, as my applications' stylesheets have lower priority than those defined in its app.ts 🤔

**Comment by Techn1x** [comment]
I'll close this as I've discovered this
https://github.com/cibernox/ember-basic-dropdown/blob/d4ee8ef2346bfbe7eadc9697de0fbaf60448e17c/docs/app/templates/public-pages/docs/installation.hbs#L27-L35

**Comment by mkszepp** [comment]
Atm there is not directly documented the migration... it is only discribed in migration to v2 addon PR https://github.com/cibernox/ember-basic-dropdown/pull/728

I will create a migration docs like i have already done in power-select https://ember-power-select.com/docs/migrate-7-0-to-8-0 (i havn't got time for that in last days, but i will do it asap, before the stable release will be done). There are more/less the same steps to do like in power select (only concurrency step can be skiped)

**Comment by Techn1x** [comment]
Thanks a bunch, I just wasn't sure if I was doing the right thing.

For the record, everything is working great for me for the betas of both this addon and power calendar!
