### ISSUE TITLE
No documentation on how to close the dropdown

### ISSUE THREAD

**Issue by ccarterc** [cibernox/ember-basic-dropdown#85]
In an old version of there was an "opened" property which could be set to false to close the dropdown.  How do you close the dropdown now?

**Comment by cibernox** [comment]
@ccarterc The component can only be closed through interaction or actions.

example:

```hbs
{{#basic-dropdown as |dropdown|}}
  <p>Lorem impsum</p>
  <p>Lorem impsum</p>
  <p>Lorem impsum</p>
  <span onclick={{dropdown.actions.close}}>x</span>
{{else}}
  Click me to toggle
{{/basic-dropdown}}
```

**Comment by ccarterc** [comment]
Ok that seems to work well enough.  Thank you so much for the info.  Would you like a PR that updates the docs and dummy examples?

**Comment by znvPredatoR** [comment]
Just wanted to say that adding some documentation on how to style / use public API to interact with the dropdown will make an integration of this plugin so much easier.

@ccarterc @cibernox

**Comment by cibernox** [comment]
@znvPredatoR I have some super-secret news for you: 

<img width="1430" alt="screen shot 2017-01-13 at 15 47 32" src="https://cloud.githubusercontent.com/assets/265339/21936046/ad597060-d9a7-11e6-92c8-f6f9e9a6f833.png">

**Comment by znvPredatoR** [comment]
@cibernox oh, wow cool! Looking forward to it 👍

**Comment by manoharank** [comment]
@cibernox Did you add any docs about publicAPI? I cannot find it.

**Comment by cibernox** [comment]
@manoharank No, but I added it just now: https://www.ember-basic-dropdown.com/docs/api-reference

**Comment by manoharank** [comment]
@cibernox  👍 

Just a suggestion. Closing the dropdown (after a selection/click) is something important when implementing custom dropdown widget. So dropdown actions deserves a separate section like `Dropdown actions` after `How to use it` section.
