### ISSUE TITLE
Dropdown cannot be triggered via mousedown or click events

### ISSUE THREAD

**Issue by tennisonchan** [cibernox/ember-basic-dropdown#86]
In our acceptance tests, we use `click('.ember-basic-dropdown-trigger')` to trigger the dropdown. It worked well in `ember-basic-dropdown` version 0.8.2. But once we updated to version 0.11.7, `click('.ember-basic-dropdown-trigger')` didn't work anymore.

The only workaround we found is to create a native js event and dispatch it to the element:
```
var event = new Event('mousedown');
document.querySelector('.ember-basic-dropdown-trigger').dispatchEvent(event);
```

**Comment by cibernox** [comment]
@tennisonchan That is correct in Ember < 2.5. In Ember it works out of the box.

The reason is that Ember 2.4 and lower fires jQuery events instead of native events, and jquery event's don't trigger handlers attached with `addEventListener` or with `onclick={{action "foo"}}`.

**Comment by tennisonchan** [comment]
@cibernox Thanks so much for the quick response! Let's close this for now.
