### ISSUE TITLE
A helper named 'basic-dropdown' could not be found

### ISSUE THREAD

**Issue by mszoernyi** [cibernox/ember-basic-dropdown#9]
Using `ember install ember-basic-dropdown` will add the addon as `devDependencies`. Build works with no issues in my addon (incl. test/dummy app). Adding my addon to a consuming app and using my component which uses ember-basic-dropdown gives me `A helper named 'basic-dropdown' could not be found`

Moving `ember-basic-dropdown` to `dependencies` and the helper is resolvable but then inside my addon the build breaks with

```
Merge error: file ember-basic-dropdown.scss exists in /home/mike/projects/remerge/ember-remerge/tmp/broccoli_merge_trees-input_base_path-0wiZhWI4.tmp/1 and /home/mike/projects/remerge/ember-remerge/tmp/broccoli_merge_trees-input_base_path-0wiZhWI4.tmp/30
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
```

**Comment by mszoernyi** [comment]
My fault, forgot about adding the dependency via `addAddonToProject`.

**Comment by cibernox** [comment]
Did you have installed ember-power-select too? I think I've seen this before but I don't remember how?

**Comment by mszoernyi** [comment]
No in this case I was just using basic-dropdown. but This might be related:

I've created a new ember project and did

`ember install ember-basic-dropdown`

Just imagine you want a dropdown for now. And then later at some point:

`ember install ember-power-select`

And you will get this error. You have to remove basic-dropdown from your `package.json`. Might be worth mentioning in the docs

**Comment by cibernox** [comment]
Can you check if this is still a problem in 0.8 of power-select / basic-dropdown? I think that now they should play nicely together.

**Comment by RobIsHere** [comment]
https://github.com/mydea/ember-date-components/issues/7

**Comment by cibernox** [comment]
@RobIsHere This issue is ancient. Do you have a reproduction?

**Comment by RobIsHere** [comment]
Google never forgets ;)

It is ancient. I just noted here to track it. Until at least another person reports, I think it is save to simply not do anything. We are on Ember 2.5 and other old things. When I update and the issue still happens, I drop a message :)

**Comment by pkappke** [comment]
Hi there, I'm having the same "A component or helper named "basic-dropdown" could not be found" message and it's not working.

I'm using running Ember: 3.0.0 and jQuery: 3.3.1.

Any help will be much appreciated.
Thanks

**Comment by cibernox** [comment]
@pkappke can you provide more information? Particularly the version of this addon you're using.

**Comment by pkappke** [comment]
Miguel, actually I made it work by editing ember-cli-build.js and adding a line on it.

I have now other problems regarding power-datepicker but this is another forum.

Thanks
