### ISSUE TITLE
Remove code that specifies different behaviour in tests inside of BasicDropdownWormhole

### ISSUE THREAD

**Issue by ArnaudWeyts** [cibernox/ember-basic-dropdown#931]
# Why 

Our visual tests render a duplicate `#ember-testing` container because of `BasicDropdownWormhole`

# What

https://github.com/cibernox/ember-basic-dropdown/blob/39b4a0e103ce7ac44890646ed11803dc3f8ff6b7/ember-basic-dropdown/src/components/basic-dropdown-wormhole.ts#L22-L29

This part of the code will result in the following structure for visual tests:

```html
<div id="ember-testing">
  <div id="ember-testing"></div>
</div>
```

I believe that this should actually be removed (except for the fastboot stuff possibly?), since visual tests use the `application.hbs` template, the wormhole should get rendered using the regular flow.

What might be required though is providing a test setup helper that does render the wormhole for regular rendering tests that don't use the `application.hbs` template.

What we've done for now as a workaround is not rendering the `BasicDropdownWormhole` in `application.hbs` in a testing environment and instead setting up the required HTML ourselves in a test helper:

```ts
import { getRootElement } from '@ember/test-helpers';

export function setupWormhole(hooks: NestedHooks) {
  hooks.beforeEach(function () {
    const wormholeBasicDropdown = document.createElement('div');
    wormholeBasicDropdown.id = 'ember-basic-dropdown-wormhole';
    getRootElement().appendChild(wormholeBasicDropdown);
  });

  hooks.afterEach(function () {
    const wormholeBasicDropdown = document.getElementById('ember-basic-dropdown-wormhole');
    wormholeBasicDropdown?.remove();
  });
}
```

This can then be setup just for rendering tests:

```js
// app/tests/helpers/index.ts
import {
  setupRenderingTest as upstreamSetupRenderingTest,
} from 'ember-qunit';

function setupRenderingTest(hooks: NestedHooks, options?: SetupTestOptions) {
  upstreamSetupRenderingTest(hooks, options);
  setupWormhole(hooks);
}
```

Would love to hear your thoughts on this, and thanks for the work on this project!

**Comment by mkszepp** [comment]
released in ´v8.3.0`
